const API_URL='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const API_KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const order=['Холодные закуски','Первые блюда','Блюда для завтраков','Вторые блюда','Гарниры','Напитки','Хлеб','Дополнительный ассортимент','Выпечка','Прочее'];
const app=document.getElementById('app');
const state={token:localStorage.getItem('stolovaya:web-token')||'',pin:'',points:[],point:'',home:null,items:[],freezer:[],incoming:[],entries:{},freezerTake:{},transferQty:{},receipt:{},screen:'login',collapsed:new Set(),search:'',message:'',busy:false,correctionDish:'',reason:'Ошибка ввода',comment:''};
const clean=s=>(s||'').replace(/^\[[^\]]+\]\s*/,'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v==null||v===''?0:Number(v);
const fmt=v=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:3});
const group=x=>(x.group_name||'').trim()||'Прочее';
async function rpc(name,body){const r=await fetch(`${API_URL}/${name}`,{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Ошибка связи с базой');return d}
function grouped(rows){const m=new Map();for(const x of rows){const g=group(x);if(!m.has(g))m.set(g,[]);m.get(g).push(x)}return [...m.entries()].sort(([a],[b])=>{const ai=order.indexOf(a),bi=order.indexOf(b);return (ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'ru')}).map(([title,items])=>({title,items:items.sort((a,b)=>clean(a.dish_name).localeCompare(clean(b.dish_name),'ru'))}))}
function draftKey(){return `stolovaya:web:${state.point}:${state.home?.businessDate||''}`}
function setMessage(x){state.message=x||'';render()}
async function login(){if(state.pin.length<4)return;state.busy=true;state.message='';render();try{const r=await rpc('public_web_login',{p_pin:state.pin});state.token=r.token;localStorage.setItem('stolovaya:web-token',state.token);await loadPoints();state.screen='point';state.pin=''}catch(e){state.message=e.message||'Не удалось войти';state.token='';localStorage.removeItem('stolovaya:web-token')}finally{state.busy=false;render()}}
async function loadPoints(){state.points=await rpc('public_point_options',{p_token:state.token});if(!state.points.length)throw new Error('Нет доступных точек')}
async function choosePoint(code){state.point=code;state.screen='loading';render();try{await loadPoint();state.screen='home'}catch(e){state.message=e.message||'Ошибка загрузки';state.screen='point'}render()}
async function loadPoint(){const [h,d,f,inc]=await Promise.all([
 rpc('public_home',{p_token:state.token,p_point_code:state.point}),
 rpc('public_daily_items_v2',{p_token:state.token,p_point_code:state.point}),
 rpc('public_freezer_items',{p_token:state.token,p_point_code:state.point}),
 rpc('public_incoming_transfers',{p_token:state.token,p_point_code:state.point})
]);state.home=h;state.items=d;state.freezer=f;state.incoming=inc;const saved=JSON.parse(localStorage.getItem(draftKey())||'null')||{};const next={};for(const x of d){next[x.dish_id]=saved[x.dish_id]||{leftover:x.leftover_qty==null?'':String(x.leftover_qty),waste:x.waste_qty==null?'':String(x.waste_qty),frozen:x.frozen_qty==null?'':String(x.frozen_qty),touched:{leftover:false,waste:false,frozen:false}}}state.entries=next;state.message=''}
function saveDraft(){if(state.home&&state.point)localStorage.setItem(draftKey(),JSON.stringify(state.entries))}
function header(){return `<header><div class="brand"><b>Столовая</b><small>${esc(state.home?.pointName||'')}</small></div>${state.home?`<div class="date-chip">${esc(state.home.businessDate)}</div>`:''}</header>`}
function back(title){return `<div class="screen-title"><button class="back" data-screen="home">←</button><h1>${esc(title)}</h1></div>`}
function loginScreen(){return `<section class="access-card"><div class="brand-login">Столовая</div><h1>Вход</h1><p>Введите код доступа. На этом устройстве вход запомнится.</p><input id="pin" class="access-pin" inputmode="numeric" autocomplete="one-time-code" value="${esc(state.pin)}" placeholder="Код доступа"><button id="login" class="primary" ${state.busy||state.pin.length<4?'disabled':''}>${state.busy?'Входим…':'Войти'}</button>${state.message?`<p class="error-text">${esc(state.message)}</p>`:''}</section>`}
function pointScreen(){return `<section class="access-card"><div class="brand-login">Столовая</div><h1>Выберите точку</h1><p>На какой точке вы сейчас работаете?</p><div class="point-choice-list">${state.points.map(p=>`<button data-point="${esc(p.point_code)}">${esc(p.point_name)}</button>`).join('')}</div><button id="logout" class="link-btn">Выйти</button></section>`}
function homeScreen(){const h=state.home;return `${header()}<section class="shift-status ${h.submitted?'done':h.filled?'partial':''}"><div><b>${h.submitted?'Смена сдана':h.filled?'Есть черновик':'Смена не сдана'}</b><span>Заполнено ${h.filled} из ${h.total}</span></div><strong>${h.submitted?'✓':`${h.filled}/${h.total}`}</strong></section>${h.pendingTransfers>0?`<button class="incoming-banner" data-screen="incoming">📦 Принять перемещения <b>${h.pendingTransfers}</b></button>`:''}<section class="home-actions"><button data-screen="inventory"><span>◉</span><div><b>Посмотреть остатки</b><small>Что доступно сегодня</small></div></button><button data-screen="${h.submitted?'submitted':'freeze-question'}"><span>✓</span><div><b>${h.submitted?'Сданные остатки':'Сдать остатки'}</b><small>${h.submitted?'Просмотр и корректировка':'Остаток, утиль, заморозка'}</small></div></button><button data-screen="transfer" ${h.submitted||h.dayClosed?'disabled':''}><span>⇄</span><div><b>Создать перемещение</b><small>Передать блюда другой точке</small></div></button></section><button id="change-point" class="wide-secondary">Сменить точку</button>${state.message?`<p class="toast">${esc(state.message)}</p>`:''}`}
function groupHtml(g,mode){const closed=state.collapsed.has(g.title)&&!state.search;return `<section class="collapsible-group"><button class="group-toggle" data-group="${encodeURIComponent(g.title)}"><span><b>${esc(g.title)}</b><small>${g.items.length}</small></span><i>${closed?'＋':'−'}</i></button>${closed?'':`<div class="cards">${g.items.map(x=>mode==='inventory'?inventoryCard(x):closingCard(x)).join('')}</div>`}</section>`}
function inventoryCard(x){return `<article class="item-card"><h3>${esc(clean(x.dish_name))}</h3><div class="meta">Доступно сегодня: <b>${fmt(x.available_qty)}</b>${n(x.freezer_balance)>0?` · Морозилка: <b>${fmt(x.freezer_balance)}</b>`:''}</div><div class="stock-breakdown"><span>пришло <b>+${fmt(x.moved_qty)}</b></span><span>перешло <b>+${fmt(x.carryover_qty)}</b></span>${n(x.freezer_out_qty)>0?`<span>из заморозки <b>+${fmt(x.freezer_out_qty)}</b></span>`:''}</div></article>`}
function closingCard(x){const e=state.entries[x.dish_id]||{leftover:'',waste:'',frozen:''};const total=n(e.leftover)+n(e.waste)+n(e.frozen);const bad=total>n(x.available_qty)+.0001;return `<article class="item-card ${bad?'bad':''}"><h3>${esc(clean(x.dish_name))}</h3><div class="meta">Доступно сегодня: <b>${fmt(x.available_qty)}</b></div><div class="fields"><label>Осталось<input data-dish="${x.dish_id}" data-field="leftover" inputmode="decimal" value="${esc(e.leftover)}" placeholder="—"></label><label>Утиль<input data-dish="${x.dish_id}" data-field="waste" inputmode="decimal" value="${esc(e.waste)}" placeholder="—"></label>${x.can_freeze?`<label>Заморозка<input data-dish="${x.dish_id}" data-field="frozen" inputmode="decimal" value="${esc(e.frozen)}" placeholder="—"></label>`:''}</div><div class="balance-row"><span>Продано: <b>${fmt(n(x.available_qty)-total)}</b></span><span>${fmt(total)} из ${fmt(x.available_qty)}</span></div>${bad?'<p class="error-text">Сумма больше доступного количества</p>':''}</article>`}
function inventoryScreen(){const groups=grouped(state.items);return `${header()}${back('Доступно сегодня')}<p class="screen-lead">Поступления, переходящий остаток, принятые перемещения и блюда из заморозки.</p><div class="group-list">${groups.map(g=>groupHtml(g,'inventory')).join('')}</div>${state.freezer.length?`<section class="freezer-block"><h2>В заморозке</h2>${state.freezer.map(x=>`<p><span>${esc(clean(x.dish_name))}</span><b>${fmt(x.quantity)}</b></p>`).join('')}</section>`:''}`}
function freezeQuestion(){return `${header()}${back('Сдача остатков')}<section class="question-card"><div class="big-icon">❄</div><h2>Доставали блюда из заморозки?</h2><p>Это добавит их к доступным сегодня блюдам.</p><button class="primary" data-screen="freezer-out">Да, доставали</button><button class="secondary" data-screen="closing">Нет, не доставали</button></section>`}
function freezerOutScreen(){return `${header()}${back('Из заморозки')}<p class="screen-lead">Укажите, сколько достали сегодня.</p>${state.freezer.length?`<div class="simple-cards">${state.freezer.map(x=>`<article><div><b>${esc(clean(x.dish_name))}</b><small>В заморозке: ${fmt(x.quantity)}</small></div><input data-freezer="${x.dish_id}" inputmode="decimal" value="${esc(state.freezerTake[x.dish_id]||'')}" placeholder="0"></article>`).join('')}</div>`:'<div class="notice">В заморозке пока ничего нет.</div>'}<div class="sticky-action"><button id="take-freezer" class="primary" ${state.busy?'disabled':''}>${state.busy?'Сохраняем…':'Продолжить'}</button></div>${state.message?`<p class="toast">${esc(state.message)}</p>`:''}`}
function closingScreen(){const rows=state.items.filter(x=>clean(x.dish_name).toLowerCase().includes(state.search.toLowerCase()));const complete=state.items.length&&state.items.every(x=>(state.entries[x.dish_id]?.leftover??'')!=='');const invalid=state.items.some(x=>{const e=state.entries[x.dish_id]||{};return n(e.leftover)+n(e.waste)+n(e.frozen)>n(x.available_qty)+.0001});const dirty=state.items.some(x=>Object.values(state.entries[x.dish_id]?.touched||{}).some(Boolean));return `${header()}${back('Сдать остатки')}<p class="screen-lead">Обязательно заполните «Осталось», в том числе нулём. Утиль и заморозку — если были.</p><input id="search" class="search" placeholder="Найти блюдо" value="${esc(state.search)}"><div class="group-list">${grouped(rows).map(g=>groupHtml(g,'closing')).join('')}</div><div class="sticky-action two"><button id="save-partial" class="secondary" ${state.busy||!dirty||invalid?'disabled':''}>Сохранить посчитанное</button><button id="finalize" class="primary" ${state.busy||!complete||invalid?'disabled':''}>Сдать всё</button></div>${state.message?`<p class="toast sticky-toast">${esc(state.message)}</p>`:''}`}
function transferScreen(){const other=state.points.filter(p=>p.point_code!==state.point);const dest=state.toPoint||other[0]?.point_code||'';state.toPoint=dest;return `${header()}${back('Новое перемещение')}<label class="select-card"><span>Куда передать</span><select id="to-point">${other.map(p=>`<option value="${esc(p.point_code)}" ${p.point_code===dest?'selected':''}>${esc(p.point_name)}</option>`).join('')}</select></label><p class="screen-lead">После отправки количество сразу уменьшится на вашей точке.</p><div class="simple-cards">${state.items.filter(x=>n(x.available_qty)>0).map(x=>`<article><div><b>${esc(clean(x.dish_name))}</b><small>Доступно: ${fmt(x.available_qty)}</small></div><input data-transfer="${x.dish_id}" inputmode="decimal" value="${esc(state.transferQty[x.dish_id]||'')}" placeholder="0"></article>`).join('')}</div><div class="sticky-action"><button id="send-transfer" class="primary" ${state.busy?'disabled':''}>${state.busy?'Отправляем…':'Отправить перемещение'}</button></div>${state.message?`<p class="toast">${esc(state.message)}</p>`:''}`}
function incomingScreen(){return `${header()}${back('Приёмка перемещений')}${state.incoming.length?state.incoming.map(t=>`<section class="receipt-card"><h2>От: ${esc(t.fromPoint)}</h2>${t.items.map(x=>`<label><span><b>${esc(clean(x.dishName))}</b><small>Отправлено: ${fmt(x.sent)}</small></span><input data-receipt="${t.id}:${x.dishId}" inputmode="decimal" value="${esc(state.receipt[`${t.id}:${x.dishId}`]??String(x.sent))}"></label>`).join('')}<button class="primary receive-transfer" data-id="${t.id}">Принять по факту</button></section>`).join(''):'<div class="notice">Новых перемещений нет.</div>'}${state.message?`<p class="toast">${esc(state.message)}</p>`:''}`}
function submittedScreen(){return `${header()}${back('Сданные остатки')}<section class="success-card"><b>✓</b><h2>Остатки сданы</h2><p>Если нашли ошибку, можно внести корректировку.</p></section><div class="submitted-list">${state.items.map(x=>`<article><div><b>${esc(clean(x.dish_name))}</b><small>Осталось ${fmt(x.leftover_qty)} · утиль ${x.waste_qty==null?'—':fmt(x.waste_qty)}${x.can_freeze?` · заморозка ${x.frozen_qty==null?'—':fmt(x.frozen_qty)}`:''}</small></div><strong>${fmt(n(x.available_qty)-n(x.leftover_qty)-n(x.waste_qty)-n(x.frozen_qty))}<small>продано</small></strong></article>`).join('')}</div><button class="wide-secondary" data-screen="correction" ${state.home.dayClosed?'disabled':''}>Внести корректировку</button>`}
function correctionScreen(){const x=state.items.find(i=>i.dish_id===state.correctionDish);const e=x?state.entries[x.dish_id]:null;return `${header()}${back('Корректировка')}<p class="warning">Изменение сохраняется в истории с причиной.</p><label class="select-card"><span>Блюдо</span><select id="correction-dish"><option value="">Выберите блюдо</option>${state.items.map(i=>`<option value="${i.dish_id}" ${i.dish_id===state.correctionDish?'selected':''}>${esc(clean(i.dish_name))}</option>`).join('')}</select></label>${x?closingCard(x):''}<label class="select-card"><span>Причина</span><select id="reason">${['Нашли остаток','Ошибка ввода','Уточнение утиля','Уточнение заморозки','Другое'].map(r=>`<option ${r===state.reason?'selected':''}>${r}</option>`).join('')}</select></label><textarea id="comment" class="comment" placeholder="Комментарий (необязательно)">${esc(state.comment)}</textarea><button id="save-correction" class="primary" ${!x||state.busy?'disabled':''}>Сохранить корректировку</button>${state.message?`<p class="toast">${esc(state.message)}</p>`:''}`}
async function savePartial(){const payload=[];for(const x of state.items){const e=state.entries[x.dish_id];if(!e)continue;const row={dishId:x.dish_id};let changed=false;for(const f of ['leftover','waste','frozen'])if(e.touched?.[f]&&e[f]!==''){row[f]=n(e[f]);changed=true}if(changed)payload.push(row)}if(!payload.length)return;state.busy=true;render();try{await rpc('public_save_closing_partial',{p_token:state.token,p_point_code:state.point,p_entries:payload,p_actor:'Буфетчик'});await loadPoint();state.message='Посчитанное сохранено'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function finalize(){const hasFrozen=state.items.some(x=>n(state.entries[x.dish_id]?.frozen)>0);if(hasFrozen&&!confirm('Проверьте свежесть замораживаемых блюд. Повторная заморозка не допускается. Продолжить?'))return;state.busy=true;render();try{const payload=[];for(const x of state.items){const e=state.entries[x.dish_id];if(!e)continue;const row={dishId:x.dish_id,leftover:n(e.leftover)};if(e.waste!=='')row.waste=n(e.waste);if(e.frozen!=='')row.frozen=n(e.frozen);payload.push(row)}await rpc('public_save_closing_partial',{p_token:state.token,p_point_code:state.point,p_entries:payload,p_actor:'Буфетчик'});await rpc('public_finalize_closing',{p_token:state.token,p_point_code:state.point,p_freshness_confirmed:hasFrozen,p_actor:'Буфетчик'});localStorage.removeItem(draftKey());await loadPoint();state.screen='submitted';state.message='Остатки сданы'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function takeFreezer(){const rows=state.freezer.filter(x=>n(state.freezerTake[x.dish_id])>0);state.busy=true;render();try{for(const x of rows){const q=n(state.freezerTake[x.dish_id]);if(q>n(x.quantity))throw new Error(`Слишком много: ${clean(x.dish_name)}`);await rpc('public_take_from_freezer',{p_token:state.token,p_point_code:state.point,p_dish_id:x.dish_id,p_quantity:q,p_actor:'Буфетчик'})}state.freezerTake={};await loadPoint();state.screen='closing'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function sendTransfer(){const rows=state.items.filter(x=>n(state.transferQty[x.dish_id])>0);if(!rows.length)return setMessage('Укажите количество хотя бы у одного блюда');for(const x of rows)if(n(state.transferQty[x.dish_id])>n(x.available_qty))return setMessage(`Недостаточно: ${clean(x.dish_name)}`);state.busy=true;render();try{await rpc('public_create_transfer',{p_token:state.token,p_point_code:state.point,p_to_point_code:state.toPoint,p_items:rows.map(x=>({dishId:x.dish_id,quantity:n(state.transferQty[x.dish_id])})),p_actor:'Буфетчик'});state.transferQty={};await loadPoint();state.screen='home';state.message='Перемещение отправлено'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function receiveTransfer(id){const t=state.incoming.find(x=>x.id===id);if(!t)return;state.busy=true;render();try{await rpc('public_receive_transfer',{p_token:state.token,p_point_code:state.point,p_transfer_id:id,p_items:t.items.map(x=>({dishId:x.dishId,quantity:n(state.receipt[`${id}:${x.dishId}`]??x.sent)})),p_actor:'Буфетчик'});state.receipt={};await loadPoint();state.screen='incoming';state.message='Перемещение принято'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function saveCorrection(){const x=state.items.find(i=>i.dish_id===state.correctionDish);if(!x)return;const e=state.entries[x.dish_id];state.busy=true;render();try{await rpc('public_correct_closing',{p_token:state.token,p_point_code:state.point,p_dish_id:x.dish_id,p_leftover:n(e.leftover),p_waste:n(e.waste),p_frozen:n(e.frozen),p_reason:state.reason,p_comment:state.comment||null,p_freshness_confirmed:n(e.frozen)>0,p_actor:'Буфетчик'});await loadPoint();state.screen='submitted';state.message='Корректировка сохранена'}catch(err){state.message=err.message}finally{state.busy=false;render()}}
function render(){if(state.screen==='login')app.innerHTML=loginScreen();else if(state.screen==='point')app.innerHTML=pointScreen();else if(state.screen==='loading')app.innerHTML='<section class="notice">Загружаем рабочий день…</section>';else if(state.screen==='home')app.innerHTML=homeScreen();else if(state.screen==='inventory')app.innerHTML=inventoryScreen();else if(state.screen==='freeze-question')app.innerHTML=freezeQuestion();else if(state.screen==='freezer-out')app.innerHTML=freezerOutScreen();else if(state.screen==='closing')app.innerHTML=closingScreen();else if(state.screen==='transfer')app.innerHTML=transferScreen();else if(state.screen==='incoming')app.innerHTML=incomingScreen();else if(state.screen==='submitted')app.innerHTML=submittedScreen();else if(state.screen==='correction')app.innerHTML=correctionScreen();bind()}
function bind(){document.getElementById('pin')?.addEventListener('input',e=>{state.pin=e.target.value.replace(/\D/g,'').slice(0,8);document.getElementById('login').disabled=state.pin.length<4});document.getElementById('pin')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.getElementById('login')?.addEventListener('click',login);document.getElementById('logout')?.addEventListener('click',()=>{localStorage.removeItem('stolovaya:web-token');state.token='';state.screen='login';render()});document.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>choosePoint(b.dataset.point));document.getElementById('change-point')?.addEventListener('click',()=>{state.screen='point';state.home=null;render()});document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen;state.search='';state.message='';render()});document.querySelectorAll('.group-toggle').forEach(b=>b.onclick=()=>{const g=decodeURIComponent(b.dataset.group);state.collapsed.has(g)?state.collapsed.delete(g):state.collapsed.add(g);render()});const s=document.getElementById('search');if(s)s.oninput=e=>{state.search=e.target.value;render()};document.querySelectorAll('[data-dish]').forEach(i=>i.oninput=e=>{const id=e.target.dataset.dish,f=e.target.dataset.field,v=e.target.value.replace(',','.');if(v&&!/^\d*(\.\d{0,3})?$/.test(v))return;state.entries[id][f]=v;state.entries[id].touched={...(state.entries[id].touched||{}),[f]:true};saveDraft()});document.querySelectorAll('[data-freezer]').forEach(i=>i.oninput=e=>state.freezerTake[e.target.dataset.freezer]=e.target.value.replace(',','.'));document.getElementById('take-freezer')?.addEventListener('click',takeFreezer);document.getElementById('save-partial')?.addEventListener('click',savePartial);document.getElementById('finalize')?.addEventListener('click',finalize);const tp=document.getElementById('to-point');if(tp)tp.onchange=e=>state.toPoint=e.target.value;document.querySelectorAll('[data-transfer]').forEach(i=>i.oninput=e=>state.transferQty[e.target.dataset.transfer]=e.target.value.replace(',','.'));document.getElementById('send-transfer')?.addEventListener('click',sendTransfer);document.querySelectorAll('[data-receipt]').forEach(i=>i.oninput=e=>state.receipt[e.target.dataset.receipt]=e.target.value.replace(',','.'));document.querySelectorAll('.receive-transfer').forEach(b=>b.onclick=()=>receiveTransfer(b.dataset.id));const cd=document.getElementById('correction-dish');if(cd)cd.onchange=e=>{state.correctionDish=e.target.value;render()};const rs=document.getElementById('reason');if(rs)rs.onchange=e=>state.reason=e.target.value;const cm=document.getElementById('comment');if(cm)cm.oninput=e=>state.comment=e.target.value;document.getElementById('save-correction')?.addEventListener('click',saveCorrection)}
(async()=>{if(!state.token){state.screen='login';render();return}state.screen='loading';render();try{await loadPoints();state.screen='point'}catch(e){localStorage.removeItem('stolovaya:web-token');state.token='';state.message='Войдите заново';state.screen='login'}render()})();
