const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('plan-app');
const state={token:sessionStorage.getItem('stolovaya:admin')||localStorage.getItem('stolovaya:admin')||'',weekStart:'',data:null,busy:false,message:'',drafts:{},adding:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',cache:'no-store',headers:{apikey:KEY,'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Операция не выполнена');return d}
function mondayOf(d){const x=new Date(d+'T12:00:00Z'),wd=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-(wd-1));return x.toISOString().slice(0,10)}
function nextMonday(){const now=new Date();const y=now.getUTCFullYear(),m=String(now.getUTCMonth()+1).padStart(2,'0'),d=String(now.getUTCDate()).padStart(2,'0');const mon=mondayOf(`${y}-${m}-${d}`);const x=new Date(mon+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+7);return x.toISOString().slice(0,10)}
function fmtDate(v){if(!v)return '';const [y,m,d]=v.split('-');return `${d}.${m}.${y}`}
function dayName(i){return ['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'][i]||''}
function num(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null}
function sum(vals){return vals.reduce((a,v)=>a+(num(v)||0),0)}
async function bootstrap(){if(state.token)return true;const buffet=localStorage.getItem('stolovaya:web-token');if(!buffet)return false;try{const r=await rpc('public_admin_session_from_buffet_token',{p_token:buffet});state.token=r.token;sessionStorage.setItem('stolovaya:admin',state.token);localStorage.setItem('stolovaya:admin',state.token);return true}catch{return false}}
function normalizeDay(day){const key=day.businessDate;const saved=(day.rows||[]).map(r=>({dishId:r.dishId,dishCode:r.dishCode||'',dishName:r.dishName||'',groupName:r.groupName||'Прочее',quantities:{...(r.quantities||{})},origins:{...(r.origins||{})},rowSource:r.source||'auto'}));for(const r of saved){for(const p of state.data.points||[]){if(!(p.code in r.origins))r.origins[p.code]=r.rowSource==='admin'?'admin':'auto'}}state.drafts[key]=saved}
async function load(){state.busy=true;state.message='';render();try{state.data=await rpc('admin_production_plan_week',{p_token:state.token,p_week_start:state.weekStart});state.drafts={};for(const d of state.data.days||[])normalizeDay(d)}catch(e){state.message=e.message;state.data=null}finally{state.busy=false;render()}}
function rowTotal(r){return sum((state.data.points||[]).map(p=>r.quantities?.[p.code]))}
function groupMap(rows){const m=new Map();for(const r of rows){const g=(r.groupName||'Прочее').trim()||'Прочее';if(!m.has(g))m.set(g,[]);m.get(g).push(r)}return m}
function qtyInput(day,r,p){const v=r.quantities?.[p.code];const o=r.origins?.[p.code]||'auto';return `<input class="qty ${o==='admin'?'edited':'auto'}" type="number" min="0" step="0.001" inputmode="decimal" data-date="${esc(day.businessDate)}" data-dish="${esc(r.dishId)}" data-point="${esc(p.code)}" value="${v===null||v===undefined?'':esc(v)}">`}
function groupRows(day,g,rows){const points=state.data.points||[];const rs=[...rows].sort((a,b)=>String(a.dishName).localeCompare(String(b.dishName),'ru'));
  const body=rs.map(r=>`<tr><td>${esc(r.dishName)}${r.dishCode?` <small>(${esc(r.dishCode)})</small>`:''}</td>${points.map(p=>`<td>${qtyInput(day,r,p)}</td>`).join('')}<td class="row-total">${rowTotal(r).toLocaleString('ru-RU',{maximumFractionDigits:3})}</td><td><button class="secondary remove-row" data-date="${esc(day.businessDate)}" data-dish="${esc(r.dishId)}">×</button></td></tr>`).join('');
  const totals=points.map(p=>sum(rs.map(r=>r.quantities?.[p.code])));
  return `<tr class="group-row"><td colspan="${points.length+3}">${esc(g)}</td></tr>${body}<tr class="group-total"><td>Итого по группе</td>${totals.map(v=>`<td>${v.toLocaleString('ru-RU',{maximumFractionDigits:3})}</td>`).join('')}<td>${sum(totals).toLocaleString('ru-RU',{maximumFractionDigits:3})}</td><td></td></tr>`}
function dayCard(day){const rows=state.drafts[day.businessDate]||[],points=state.data.points||[],groups=groupMap(rows);const allTotals=points.map(p=>sum(rows.map(r=>r.quantities?.[p.code])));const status=day.status||'draft';
  const table=rows.length?`<div class="table-wrap"><table class="plan-table"><thead><tr><th>Блюдо</th>${points.map(p=>`<th>${esc(p.name)}</th>`).join('')}<th>Всего</th><th></th></tr></thead><tbody>${[...groups.entries()].map(([g,rs])=>groupRows(day,g,rs)).join('')}<tr class="day-total"><td>ИТОГО ЗА ДЕНЬ</td>${allTotals.map(v=>`<td>${v.toLocaleString('ru-RU',{maximumFractionDigits:3})}</td>`).join('')}<td>${sum(allTotals).toLocaleString('ru-RU',{maximumFractionDigits:3})}</td><td></td></tr></tbody></table></div>`:'<div class="empty-day">По перемещениям две недели назад блюд не найдено. Добавьте их вручную.</div>';
  const opts=(state.data.dishes||[]).map(d=>`<option value="${esc(d.id)}">${esc(d.name)}${d.code?` (${esc(d.code)})`:''}</option>`).join('');
  return `<section class="card day-card"><div class="day-head"><div><h2>${dayName(day.dayNo)}</h2><small>${fmtDate(day.businessDate)} · ориентир: ${fmtDate(day.sourceDate)} (2 недели назад)</small></div><div class="day-actions"><span class="status ${esc(status)}">${status==='production_draft'?'Черновик акта приготовления':'Черновик плана'}</span><button class="secondary save-day" data-date="${esc(day.businessDate)}">Сохранить</button><button class="to-production" data-date="${esc(day.businessDate)}">В производство</button></div></div>${table}<div class="add-row"><label>Добавить блюдо<select data-add-select="${esc(day.businessDate)}"><option value="">Выберите блюдо</option>${opts}</select></label><button class="secondary add-dish" data-date="${esc(day.businessDate)}">＋ Добавить строку</button></div></section>`}
function app(){return `<main class="plan"><header class="top"><div><a class="section-back" href="../">← Назад в админку</a><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>План</h1><p class="subtitle">Прототип недельного плана производства</p></div><div class="week-tools"><label>Неделя с понедельника<input id="week-start" type="date" value="${esc(state.weekStart)}"></label><button id="load-week" class="secondary">Открыть неделю</button></div></header><div class="prototype-note">Сейчас это прототип. Блюда и исходные количества берутся из такого же дня две недели назад. Красные значения — подставлены системой, синие — изменены администратором. Кнопка «В производство» пока создаёт только локальный черновик акта приготовления и ничего не отправляет в iiko.</div><div class="legend"><span><i class="dot auto"></i>Система</span><span><i class="dot edited"></i>Изменено администратором</span></div>${state.message?`<p class="message">${esc(state.message)}</p>`:''}${(state.data?.days||[]).map(dayCard).join('')}</main>`}
function render(){root.innerHTML=state.data?app():`<main class="plan"><section class="card loading">${state.busy?'Загрузка плана…':state.message?esc(state.message):'Загрузка…'}</section></main>`;bind()}
function currentRows(date){return (state.drafts[date]||[]).map(r=>({dishId:r.dishId,dishCode:r.dishCode,dishName:r.dishName,groupName:r.groupName,quantities:r.quantities,origins:r.origins,source:r.rowSource}))}
async function saveDay(date,production=false){state.busy=true;state.message='';render();try{const name=production?'admin_send_production_plan_day':'admin_save_production_plan_day';const res=await rpc(name,{p_token:state.token,p_business_date:date,p_rows:currentRows(date),p_actor:'Администратор'});const msg=production?`На ${fmtDate(date)} создан черновик акта приготовления. В iiko ничего не отправлено.`:`План на ${fmtDate(date)} сохранён.`;await load();state.message=res?.note&&production?`${msg} ${res.note}`:msg}catch(e){state.message=e.message}finally{state.busy=false;render()}}
function addDish(date,id){if(!id)return;const dish=(state.data.dishes||[]).find(x=>String(x.id)===String(id));if(!dish)return;const rows=state.drafts[date]||[];if(rows.some(r=>String(r.dishId)===String(id))){state.message='Это блюдо уже есть в таблице';render();return}const q={},o={};for(const p of state.data.points||[]){q[p.code]=null;o[p.code]='admin'}rows.push({dishId:dish.id,dishCode:dish.code||'',dishName:dish.name,groupName:dish.groupName||'Прочее',quantities:q,origins:o,rowSource:'admin'});state.drafts[date]=rows;render()}
function bind(){document.getElementById('week-start')?.addEventListener('change',e=>state.weekStart=mondayOf(e.target.value));document.getElementById('load-week')?.addEventListener('click',load);document.querySelectorAll('.qty').forEach(inp=>{inp.oninput=()=>{const rows=state.drafts[inp.dataset.date]||[],r=rows.find(x=>String(x.dishId)===String(inp.dataset.dish));if(!r)return;r.quantities[inp.dataset.point]=num(inp.value);r.origins[inp.dataset.point]='admin';inp.classList.remove('auto');inp.classList.add('edited');const tr=inp.closest('tr');const rt=tr?.querySelector('.row-total');if(rt)rt.textContent=rowTotal(r).toLocaleString('ru-RU',{maximumFractionDigits:3})};inp.onchange=()=>render()});document.querySelectorAll('.save-day').forEach(b=>b.onclick=()=>saveDay(b.dataset.date,false));document.querySelectorAll('.to-production').forEach(b=>b.onclick=()=>saveDay(b.dataset.date,true));document.querySelectorAll('.add-dish').forEach(b=>b.onclick=()=>{const sel=document.querySelector(`[data-add-select="${CSS.escape(b.dataset.date)}"]`);addDish(b.dataset.date,sel?.value||'')});document.querySelectorAll('.remove-row').forEach(b=>b.onclick=()=>{state.drafts[b.dataset.date]=(state.drafts[b.dataset.date]||[]).filter(r=>String(r.dishId)!==String(b.dataset.dish));render()})}
(async()=>{state.weekStart=nextMonday();if(!(await bootstrap())){location.href='../';return}await load()})();
