const FN='https://rgluzdxikpagugpmusbp.supabase.co/functions/v1/stolovaya-kitchen-stock-report';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('kitchen-stock-app');
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const state={token:sessionStorage.getItem('stolovaya:admin')||localStorage.getItem('stolovaya:admin')||'',kitchen:'BUKHARA',date:today,data:null,busy:false,message:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qty=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(Number(v||0));
const diffText=v=>{const n=Number(v||0);return `${n>0?'+':''}${qty(n)}`};
const diffClass=v=>Number(v||0)>0?'pos':Number(v||0)<0?'neg':'zero';
function fmtDate(v){if(!v)return '';const[y,m,d]=v.split('-');return `${d}.${m}.${y}`}
async function load(){if(!state.token){location.href='../';return}state.busy=true;state.message='';render();try{const r=await fetch(FN,{method:'POST',cache:'no-store',headers:{apikey:KEY,'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify({adminToken:state.token,businessDate:state.date,kitchenCode:state.kitchen})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.message||'Не удалось получить отчёт');state.data=d}catch(e){state.data=null;state.message=e.message||'Не удалось получить отчёт'}finally{state.busy=false;render()}}
function summary(t){return `<div class="summary-strip"><div class="summary-item"><small>На начало дня</small><b>${qty(t.openingQty)}</b></div><div class="summary-item"><small>Приготовлено</small><b>${qty(t.producedQty)}</b></div><div class="summary-item"><small>Перемещено</small><b>${qty(t.transferredQty)}</b></div><div class="summary-item"><small>На конец дня</small><b>${qty(t.closingQty)}</b></div></div>`}
function table(d){const rows=d.rows||[],t=d.totals||{};return `<section class="card">${summary(t)}<div class="table-wrap"><table class="stock-table"><thead><tr><th>Блюдо / продукт</th><th>На начало</th><th>Приготовлено</th><th>Перемещено</th><th>На конец</th><th>Разница</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><b>${esc(r.name||'Без названия')}</b>${r.code?`<span class="dish-code">${esc(r.code)}</span>`:''}</td><td>${qty(r.openingQty)}</td><td>${qty(r.producedQty)}</td><td>${qty(r.transferredQty)}</td><td>${qty(r.closingQty)}</td><td class="diff ${diffClass(r.difference)}">${diffText(r.difference)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">По выбранной кухне за эту дату остатков и движения нет.</td></tr>'}<tr class="total-row"><td>Итого</td><td>${qty(t.openingQty)}</td><td>${qty(t.producedQty)}</td><td>${qty(t.transferredQty)}</td><td>${qty(t.closingQty)}</td><td class="diff ${diffClass(t.difference)}">${diffText(t.difference)}</td></tr><tr class="difference-row"><td colspan="5">Разница между остатком на начало и конец дня</td><td class="diff ${diffClass(t.difference)}">${diffText(t.difference)}</td></tr></tbody></table></div><p class="source-note">Начальный и конечный остаток — напрямую из iiko по складу «${esc(d.warehouse)}». Приготовлено — акты приготовления iiko. Перемещено — исходящие перемещения с этого кухонного склада.</p></section>`}
function app(){const name=state.kitchen==='BUKHARA'?'Бухара':'Правда';return `<main class="admin"><header class="top"><div><a class="section-back" href="../">← Назад в админку</a><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Остатки кухонь</h1><p class="subtitle">${esc(name)} · ${esc(fmtDate(state.date))}</p></div></header><section class="card"><div class="filters"><div class="kitchen-switch"><button data-kitchen="BUKHARA" class="${state.kitchen==='BUKHARA'?'active':''}">Бухара</button><button data-kitchen="PRAVDA" class="${state.kitchen==='PRAVDA'?'active':''}">Правда</button></div><label>Дата<input id="report-date" type="date" max="${esc(today)}" value="${esc(state.date)}"></label><button id="refresh" ${state.busy?'disabled':''}>${state.busy?'Загружаем…':'Обновить'}</button></div></section>${state.message?`<p class="message error">${esc(state.message)}</p>`:''}${state.busy&&!state.data?'<section class="card loading">Получаем остатки из iiko…</section>':state.data?table(state.data):''}</main>`}
function bind(){document.querySelectorAll('[data-kitchen]').forEach(b=>b.onclick=()=>{if(state.kitchen===b.dataset.kitchen)return;state.kitchen=b.dataset.kitchen;load()});document.getElementById('report-date')?.addEventListener('change',e=>{state.date=e.target.value;load()});document.getElementById('refresh')?.addEventListener('click',load)}
function render(){root.innerHTML=app();bind()}
load();