const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('kitchen-stock-app');
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nextDay=(()=>{const [y,m,d]=today.split('-').map(Number);const x=new Date(Date.UTC(y,m-1,d+1));return x.toISOString().slice(0,10)})();
const state={token:sessionStorage.getItem('stolovaya:admin')||localStorage.getItem('stolovaya:admin')||'',kitchen:'BUKHARA',date:today,data:null,busy:false,message:'',showPlus:false,showMinus:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qty=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(Number(v||0));
const signed=v=>{const n=Number(v||0);return `${n>0?'+':''}${qty(n)}`};
const diffClass=v=>Math.abs(Number(v||0))<0.0005?'zero':Number(v||0)>0?'pos':'neg';
const round=v=>Math.round((Number(v||0)+Number.EPSILON)*1000)/1000;
function fmtDate(v){if(!v)return '';const[y,m,d]=v.split('-');return `${d}.${m}.${y}`}
async function rpc(name,body){const r=await fetch(API+name,{method:'POST',cache:'no-store',headers:{apikey:KEY,'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Не удалось получить отчёт');return d}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function load(){if(!state.token){location.href='../';return}state.busy=true;state.message='';state.data=null;render();try{await rpc('admin_request_kitchen_stock_report',{p_token:state.token,p_business_date:state.date,p_kitchen_code:state.kitchen});let d=null;for(let i=0;i<24;i++){await sleep(i?900:300);d=await rpc('admin_get_kitchen_stock_report',{p_token:state.token,p_business_date:state.date,p_kitchen_code:state.kitchen});if(d?.ok)break;if(d?.status==='error')throw new Error(d.message||'Ошибка загрузки iiko')}if(!d?.ok)throw new Error('iiko отвечает дольше обычного. Нажмите «Обновить» ещё раз.');state.data=d}catch(e){state.message=e.message||'Не удалось получить отчёт'}finally{state.busy=false;render()}}
function summary(t){return `<div class="summary-strip"><div class="summary-item"><small>На начало</small><b>${qty(t.openingQty)}</b></div><div class="summary-item"><small>Приготовлено</small><b>${qty(t.producedQty)}</b></div><div class="summary-item"><small>Приход перемещениями</small><b>${qty(t.incomingTransferQty)}</b></div><div class="summary-item"><small>Ушло перемещениями</small><b>${qty(t.outgoingTransferQty)}</b></div><div class="summary-item"><small>На конец</small><b>${qty(t.closingQty)}</b></div><div class="summary-item audit ${diffClass(t.unexplainedQty)}"><small>Контрольная разница</small><b>${signed(t.unexplainedQty)}</b></div></div>`}
function viewRow(r){return {...r}}
function rowHtml(raw){const r=viewRow(raw);return `<tr><td><b>${esc(r.name||'Без названия')}</b>${r.code?`<span class="dish-code">${esc(r.code)}</span>`:''}</td><td>${qty(r.openingQty)}</td><td>${qty(r.producedQty)}</td><td>${qty(r.incomingTransferQty)}</td><td>${qty(r.outgoingTransferQty)}</td><td>${qty(r.salesQty)}</td><td>${qty(r.writeOffQty)}</td><td>${qty(r.otherIncomingQty)}</td><td>${qty(r.otherOutgoingQty)}</td><td>${qty(r.closingQty)}</td><td class="diff ${diffClass(r.difference)}">${signed(r.difference)}</td><td class="audit-cell ${diffClass(r.unexplainedQty)}">${signed(r.unexplainedQty)}</td></tr>`}
function groupTotal(rows){return rows.map(viewRow).reduce((z,r)=>({openingQty:round(z.openingQty+r.openingQty),producedQty:round(z.producedQty+r.producedQty),incomingTransferQty:round(z.incomingTransferQty+r.incomingTransferQty),outgoingTransferQty:round(z.outgoingTransferQty+r.outgoingTransferQty),salesQty:round(z.salesQty+r.salesQty),writeOffQty:round(z.writeOffQty+r.writeOffQty),otherIncomingQty:round(z.otherIncomingQty+r.otherIncomingQty),otherOutgoingQty:round(z.otherOutgoingQty+r.otherOutgoingQty),closingQty:round(z.closingQty+r.closingQty),difference:round(z.difference+r.difference),unexplainedQty:round(z.unexplainedQty+r.unexplainedQty)}),{openingQty:0,producedQty:0,incomingTransferQty:0,outgoingTransferQty:0,salesQty:0,writeOffQty:0,otherIncomingQty:0,otherOutgoingQty:0,closingQty:0,difference:0,unexplainedQty:0})}
function totalCells(t){return `<td>${qty(t.openingQty)}</td><td>${qty(t.producedQty)}</td><td>${qty(t.incomingTransferQty)}</td><td>${qty(t.outgoingTransferQty)}</td><td>${qty(t.salesQty)}</td><td>${qty(t.writeOffQty)}</td><td>${qty(t.otherIncomingQty)}</td><td>${qty(t.otherOutgoingQty)}</td><td>${qty(t.closingQty)}</td><td class="diff ${diffClass(t.difference)}">${signed(t.difference)}</td><td class="audit-cell ${diffClass(t.unexplainedQty)}">${signed(t.unexplainedQty)}</td>`}
function filteredRows(rows){if(!state.showPlus&&!state.showMinus)return rows;return rows.filter(r=>{const d=Number(r.difference||0);return(state.showPlus&&d>0.0005)||(state.showMinus&&d<-0.0005)})}
function groupedRows(rows){const groups=new Map();for(const r of rows){const g=(r.groupName||'Прочее').trim()||'Прочее';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r)}return [...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ru')).map(([name,items])=>{items.sort((a,b)=>String(a.name).localeCompare(String(b.name),'ru'));const t=groupTotal(items);return `<tr class="group-title"><td colspan="12">${esc(name)}</td></tr>${items.map(rowHtml).join('')}<tr class="group-total"><td>Итого по группе</td>${totalCells(t)}</tr>`}).join('')}
function typeNote(d){const a=(d.operationTypes||[]).filter(x=>Number(x.incoming||0)||Number(x.outgoing||0));if(!a.length)return '';return `<details class="op-types"><summary>Какие типы складских документов iiko вошли в расчёт</summary>${a.map(x=>`<div><b>${esc(x.documentType)}</b><span>приход ${qty(x.incoming)} · расход ${qty(x.outgoing)}</span></div>`).join('')}</details>`}
function filters(){return `<div class="difference-filters"><label class="diff-filter plus"><input id="show-plus" type="checkbox" ${state.showPlus?'checked':''}><span>Показать разницу +</span></label><label class="diff-filter minus"><input id="show-minus" type="checkbox" ${state.showMinus?'checked':''}><span>Показать разницу −</span></label></div>`}
function table(d){const allRows=d.rows||[],rows=filteredRows(allRows),full=groupTotal(allRows),filtered=groupTotal(rows),active=state.showPlus||state.showMinus;return `<section class="card">${summary(full)}${filters()}<div class="table-wrap"><table class="stock-table"><thead><tr><th>Блюдо / продукт</th><th>Начало</th><th>Приготовлено</th><th>Приход<br>перемещ.</th><th>Ушло<br>перемещ.</th><th>Реализация</th><th>Списано</th><th>Прочий<br>приход</th><th>Прочий<br>расход</th><th>Конец</th><th>Δ начало/<br>конец</th><th>Контроль</th></tr></thead><tbody>${rows.length?groupedRows(rows):'<tr><td colspan="12" class="empty">Нет блюд с выбранной разницей.</td></tr>'}<tr class="total-row"><td>${active?'ИТОГО ПО ПОКАЗАННЫМ':'ИТОГО ПО КУХНЕ'}</td>${totalCells(active?filtered:full)}</tr></tbody></table></div><div class="audit-help"><b>Контроль:</b> конец − (начало + приготовлено + приход перемещениями + прочий приход − исходящие перемещения − реализация − списания − прочий расход). В норме должен быть 0.</div>${typeNote(d)}<p class="source-note">Начальный и конечный остаток и вся складская расшифровка получаются напрямую из iiko по складу «${esc(d.warehouse)}».</p></section>`}
function app(){const name=state.kitchen==='BUKHARA'?'Бухара':'Правда';return `<main class="admin"><header class="top"><div><a class="section-back" href="../">← Назад в админку</a><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Остатки кухонь</h1><p class="subtitle">${esc(name)} · ${esc(fmtDate(state.date))}</p></div></header><section class="card"><div class="filters"><div class="kitchen-switch"><button data-kitchen="BUKHARA" class="${state.kitchen==='BUKHARA'?'active':''}">Бухара</button><button data-kitchen="PRAVDA" class="${state.kitchen==='PRAVDA'?'active':''}">Правда</button></div><label>Дата<input id="report-date" type="date" max="${esc(nextDay)}" value="${esc(state.date)}"></label><button id="refresh" ${state.busy?'disabled':''}>${state.busy?'Загружаем…':'Обновить'}</button></div></section>${state.message?`<p class="message error">${esc(state.message)}</p>`:''}${state.busy?'<section class="card loading">Получаем складские движения из iiko…</section>':state.data?table(state.data):''}</main>`}
function bind(){document.querySelectorAll('[data-kitchen]').forEach(b=>b.onclick=()=>{if(state.kitchen===b.dataset.kitchen)return;state.kitchen=b.dataset.kitchen;load()});document.getElementById('report-date')?.addEventListener('change',e=>{state.date=e.target.value;load()});document.getElementById('refresh')?.addEventListener('click',load);document.getElementById('show-plus')?.addEventListener('change',e=>{state.showPlus=e.target.checked;render()});document.getElementById('show-minus')?.addEventListener('change',e=>{state.showMinus=e.target.checked;render()})}
function render(){root.innerHTML=app();bind()}
load();