const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('control-app');
const state={token:sessionStorage.getItem('stolovaya:admin')||localStorage.getItem('stolovaya:admin')||'',data:null,busy:false,message:'',lockDate:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Операция не выполнена');return d}
async function bootstrap(){if(state.token)return true;const buffet=localStorage.getItem('stolovaya:web-token');if(!buffet)return false;try{const r=await rpc('public_admin_session_from_buffet_token',{p_token:buffet});state.token=r.token;sessionStorage.setItem('stolovaya:admin',state.token);localStorage.setItem('stolovaya:admin',state.token);return true}catch{return false}}
function fmtAt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function fmtDate(v){if(!v)return 'не закрыт';const [y,m,d]=String(v).split('-');return `${d}.${m}.${y}`}
async function load(){state.busy=true;state.message='';render();try{state.data=await rpc('admin_control_dashboard',{p_token:state.token});state.lockDate=state.data.periodLockedThrough||''}catch(e){state.message=e.message;if(/недействительн/i.test(e.message||'')){state.token='';sessionStorage.removeItem('stolovaya:admin');localStorage.removeItem('stolovaya:admin')}}finally{state.busy=false;render()}}
async function saveLock(){const v=document.getElementById('period-lock')?.value||'';const current=state.data?.periodLockedThrough||'';const text=v?`Закрыть период по ${fmtDate(v)}? После этого буфетчики не смогут менять даты до этой включительно.`:'Открыть ранее закрытый период?';if(!confirm(text))return;state.busy=true;state.message='';render();try{await rpc('admin_control_set_period_lock',{p_token:state.token,p_locked_through:v||null,p_actor:'Администратор'});await load();state.message=v?`Период закрыт по ${fmtDate(v)}`:'Ограничение периода снято'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
function alertCard(a){const journal=`../journal/?from=${encodeURIComponent(a.businessDate||'')}&to=${encodeURIComponent(a.businessDate||'')}&point=${encodeURIComponent(a.pointCode||'')}`;return `<article class="alert ${a.severity==='error'?'error':''}"><div class="alert-head"><div><h3>${a.severity==='error'?'⛔':'⚠'} ${esc(a.title)}</h3><div class="alert-meta">${esc(a.pointName||'')} · ${esc(fmtDate(a.businessDate))}</div></div><a class="secondary admin-link" href="${journal}">Открыть журнал</a></div><p>${esc(a.description||'')}</p></article>`}
function app(){const d=state.data||{};const s=d.summary||{};const alerts=d.alerts||[];const i=d.iiko||{};return `<main class="admin"><header class="top"><div><a class="section-back" href="../">← Назад в админку</a><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Контроль</h1><p class="subtitle">Ошибки, незакрытые дни, iiko и закрытие периода</p></div><div class="toolbar"><button id="refresh" class="secondary" ${state.busy?'disabled':''}>↻ Обновить</button></div></header>${state.message?`<p class="message">${esc(state.message)}</p>`:''}<section class="control-grid"><div class="metric"><b>${s.errors||0}</b><small>критических ошибок</small></div><div class="metric"><b>${s.warnings||0}</b><small>предупреждений</small></div><div class="metric"><b>${s.openDays||0}</b><small>незакрытых дней</small></div><div class="metric"><b>${s.partialDays||0}</b><small>частично заполненных</small></div><div class="metric"><b>${s.pendingTransfers||0}</b><small>непринятых перемещений</small></div><div class="metric"><b>${i.lateDocuments||0}</b><small>документов задним числом</small></div></section><section class="card"><h2>Ошибки и предупреждения</h2>${alerts.length?`<div class="alert-list">${alerts.map(alertCard).join('')}</div>`:'<p class="ok-note">✓ Активных ошибок и предупреждений нет.</p>'}</section><section class="card"><h2>Синхронизация iiko</h2><div class="status-row"><div class="status-box"><b>Последнее движение</b><p>${esc(fmtAt(i.lastMovementLoadedAt))}</p><small>Дата документа: ${esc(fmtDate(i.lastMovementDate))}</small></div><div class="status-box"><b>Последний импорт iiko</b><p>${esc(fmtAt(i.lastImportAt))}</p><small>Статус: ${esc(i.lastImportStatus||'нет данных')}</small></div></div>${(i.lateDocuments||0)>0?`<p class="danger-note">⚠ Найдено документов, появившихся после своей рабочей даты: <b>${i.lateDocuments}</b>. Они выведены выше для проверки.</p>`:'<p class="ok-note">✓ Исторических документов, требующих проверки, не найдено.</p>'}</section><section class="card"><h2>Закрытие периода</h2><p>Закрытый период исключается из автоматических предупреждений, а буфетчики не смогут менять эти даты. Для старых изменений период сначала нужно открыть администратором.</p><p><b>Сейчас закрыто по:</b> ${esc(fmtDate(d.periodLockedThrough))}</p><div class="period-form"><label>Закрыть по дату<input id="period-lock" type="date" max="${esc(d.today||'')}" value="${esc(state.lockDate||'')}"></label><button id="save-lock" ${state.busy?'disabled':''}>Сохранить</button>${d.periodLockedThrough?'<button id="clear-lock" class="secondary" '+(state.busy?'disabled':'')+'>Открыть период</button>':''}</div></section></main>`}
function render(){if(!state.data){root.innerHTML=`<main class="admin"><section class="card loading">${state.busy?'Проверяем данные…':state.message?esc(state.message):'Загрузка…'}</section></main>`;return}root.innerHTML=app();bind()}
function bind(){document.getElementById('refresh')?.addEventListener('click',load);document.getElementById('period-lock')?.addEventListener('change',e=>state.lockDate=e.target.value);document.getElementById('save-lock')?.addEventListener('click',saveLock);document.getElementById('clear-lock')?.addEventListener('click',()=>{const x=document.getElementById('period-lock');if(x)x.value='';state.lockDate='';saveLock()})}
(async()=>{if(!(await bootstrap())){location.href='../';return}await load()})();
