const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('journal-app');
function shift(days){const d=new Date();d.setDate(d.getDate()+days);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow'}).format(d)}
function monthStart(){const today=shift(0);return today.slice(0,8)+'01'}
const state={
  token:localStorage.getItem('stolovaya:admin')||sessionStorage.getItem('stolovaya:admin')||'',
  pin:'',from:monthStart(),to:shift(0),type:'',point:'',data:null,busy:false,message:'',
  open:new Set(),historyOpen:new Set(),histories:{},historyBusy:new Set(),
  employees:[],actor:localStorage.getItem('stolovaya:journal-actor')||'',
  editing:new Set(),saving:new Set(),drafts:{}
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Не удалось выполнить запрос');return d}
function saveAdminToken(t){state.token=t;localStorage.setItem('stolovaya:admin',t);sessionStorage.setItem('stolovaya:admin',t)}
function clearAdminToken(){state.token='';localStorage.removeItem('stolovaya:admin');sessionStorage.removeItem('stolovaya:admin')}
async function bootstrapFromStolovaya(){const buffetToken=localStorage.getItem('stolovaya:web-token');if(!buffetToken)return false;try{const r=await rpc('public_admin_session_from_buffet_token',{p_token:buffetToken});saveAdminToken(r.token);await load();return true}catch(e){return false}}
async function login(){if(state.pin.length<4)return;state.busy=true;state.message='';render();try{const r=await rpc('public_admin_web_login',{p_pin:state.pin});saveAdminToken(r.token);state.pin='';await load()}catch(e){state.message=e.message;clearAdminToken()}finally{state.busy=false;render()}}
async function loadEmployees(){try{const d=await rpc('admin_employee_directory',{p_token:state.token});state.employees=(d.employees||[]).filter(e=>e.isActive);if(state.actor&&!state.employees.some(e=>e.fullName===state.actor)){state.actor='';localStorage.removeItem('stolovaya:journal-actor')}}catch(e){state.employees=[]}}
async function load(){if(!state.token)return;state.busy=true;state.message='';render();try{const [journal]=await Promise.all([rpc('admin_document_journal',{p_token:state.token,p_from:state.from,p_to:state.to,p_type:state.type||null,p_point_code:state.point||null}),state.employees.length?Promise.resolve():loadEmployees()]);state.data=journal}catch(e){state.data=null;state.message=e.message;if(/недействительн/i.test(state.message)){clearAdminToken();if(await bootstrapFromStolovaya())return}}finally{state.busy=false;render()}}
function loginScreen(){return `<main class="journal"><section class="card login"><h1>Журнал документов</h1><p>Если вы уже входили в «Столовую» на этом устройстве, журнал откроется автоматически. Иначе введите код доступа.</p><input id="pin" type="password" inputmode="numeric" value="${esc(state.pin)}" placeholder="Код доступа"><button id="login" ${state.busy||state.pin.length<4?'disabled':''}>${state.busy?'Входим…':'Войти'}</button>${state.message?`<p class="message">${esc(state.message)}</p>`:''}</section></main>`}
function typeName(t){return ({movement:'Перемещение',closing:'Закрытие дня',internal_transfer:'Внутреннее перемещение',freeze_in:'Заморозка',freeze_out:'Разморозка',freeze_adjustment:'Корректировка морозилки',correction:'Корректировка'})[t]||t}
function historyKey(d){return d.doc_type+'|'+d.doc_id}
function itemQty(i){return i.qty??i.sent??i.leftover??i.received??''}
function draftKey(d,i){return historyKey(d)+'|'+String(i.itemId)}
function findDoc(type,id){return (state.data?.documents||[]).find(d=>d.doc_type===type&&String(d.doc_id)===String(id))}
function details(d){const x=d.details||{};const items=x.items||[];return `<div class="details"><div class="details-grid"><div><b>Тип</b><br>${esc(typeName(d.doc_type))}</div><div><b>Кто создал</b><br>${esc(d.actor||'—')}</div></div>${items.length?`<div class="items">${items.map(i=>`<div><span>${esc(i.dish||'')}</span><b>${esc(itemQty(i))}</b></div>`).join('')}</div>`:`<pre>${esc(JSON.stringify(x,null,2))}</pre>`}</div>`}
function fmtAt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function sourceName(s){return ({mobile:'Приложение',database:'База',iiko_xls:'iiko / база',iiko:'iiko / база',excel:'База',admin:'Администратор'})[s]||s||'—'}
function historyHtml(d){const key=historyKey(d);if(state.historyBusy.has(key))return `<div class="details"><p>Загружаем историю…</p></div>`;const info=state.histories[key];if(info?.error)return `<div class="details"><p class="message">${esc(info.error)}</p></div>`;const events=info?.events||[];if(!events.length)return `<div class="details"><p>История изменений пока не зафиксирована.</p></div>`;return `<div class="details"><h3>История изменений</h3><div class="items history-list">${events.map(e=>`<div><span><b>${esc(e.action||'Изменение')}</b><small>${esc(fmtAt(e.at))} · ${esc(e.actor||'Система')} · ${esc(sourceName(e.source))}${e.note?`<br>${esc(e.note)}`:''}</small></span></div>`).join('')}</div></div>`}
async function refreshHistory(d){const key=historyKey(d);state.historyBusy.add(key);render();try{state.histories[key]=await rpc('admin_document_history',{p_token:state.token,p_doc_type:d.doc_type,p_doc_id:String(d.doc_id)})}catch(e){state.histories[key]={events:[],error:e.message}}finally{state.historyBusy.delete(key);render()}}
async function toggleHistory(type,id){const d=findDoc(type,id);if(!d)return;const key=historyKey(d);if(state.historyOpen.has(key)){state.historyOpen.delete(key);render();return}state.historyOpen.add(key);if(!state.histories[key])await refreshHistory(d);else render()}
function startEdit(d){const key=historyKey(d);state.editing.add(key);for(const i of d.details?.items||[]){if(i.editable)state.drafts[draftKey(d,i)]=String(itemQty(i))}state.message='';render()}
function cancelEdit(d){const key=historyKey(d);state.editing.delete(key);for(const i of d.details?.items||[])delete state.drafts[draftKey(d,i)];render()}
async function saveEdit(d){const key=historyKey(d);if(!state.actor){state.message='Выберите сотрудника, который вносит изменение';render();return}const items=(d.details?.items||[]).filter(i=>i.editable);const changes=[];for(const i of items){const raw=state.drafts[draftKey(d,i)];const value=Number(String(raw).replace(',','.'));const oldValue=Number(itemQty(i));if(!Number.isFinite(value)){state.message='Проверьте количество в документе';render();return}if(value!==oldValue)changes.push({item:i,value})}if(!changes.length){cancelEdit(d);return}state.saving.add(key);state.message='';render();try{for(const ch of changes){await rpc('admin_update_document_quantity',{p_token:state.token,p_doc_type:d.doc_type,p_doc_id:String(d.doc_id),p_item_id:String(ch.item.itemId),p_new_qty:ch.value,p_actor:state.actor})}localStorage.setItem('stolovaya:journal-actor',state.actor);state.editing.delete(key);for(const i of items)delete state.drafts[draftKey(d,i)];delete state.histories[key];await load();const fresh=findDoc(d.doc_type,d.doc_id);if(fresh&&state.historyOpen.has(key))await refreshHistory(fresh)}catch(e){state.message=e.message}finally{state.saving.delete(key);render()}}
function app(){const docs=state.data?.documents||[];return `<main class="journal"><header class="top"><div><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Журнал документов</h1></div><a class="back secondary" href="../">Назад</a></header><section class="card"><div class="filters"><label>С<input id="from" type="date" value="${state.from}"></label><label>По<input id="to" type="date" value="${state.to}"></label><label>Тип<select id="type"><option value="">Все документы</option>${(state.data?.types||[]).map(t=>`<option value="${esc(t.code)}" ${state.type===t.code?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Точка<select id="point"><option value="">Все точки</option>${(state.data?.points||[]).map(p=>`<option value="${esc(p.code)}" ${state.point===p.code?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label></div><div class="actions"><button id="apply">Применить</button><button id="reset" class="secondary">Сбросить</button></div></section><section class="card summary"><span>Документов: <b>${docs.length}</b></span><span>${esc(state.from)} — ${esc(state.to)}</span></section>${state.message?`<p class="message">${esc(state.message)}</p>`:''}<section class="docs">${docs.length?docs.map(d=>{const k=historyKey(d);return `<article class="doc"><div class="doc-head"><div class="doc-date">${esc(d.business_date)}</div><div class="doc-title"><b>${esc(d.title)}</b><small>${esc(typeName(d.doc_type))}</small></div><div>${esc(d.from_point||'')} ${d.from_point&&d.to_point?'→ ':''}${esc(d.to_point||'')}</div><button data-open="${esc(k)}">${state.open.has(k)?'Скрыть документ':'Открыть'}</button><button class="secondary" data-history-type="${esc(d.doc_type)}" data-history-id="${esc(d.doc_id)}">${state.historyOpen.has(k)?'Скрыть историю':'История изменений'}</button></div>${state.open.has(k)?details(d):''}${state.historyOpen.has(k)?historyHtml(d):''}</article>`}).join(''):'<div class="card empty">За выбранный период документов нет.</div>'}</section></main>`}
function bind(){const p=document.getElementById('pin');if(p){p.oninput=e=>{state.pin=e.target.value.replace(/\D/g,'').slice(0,8);document.getElementById('login').disabled=state.pin.length<4};p.onkeydown=e=>{if(e.key==='Enter')login()}}document.getElementById('login')?.addEventListener('click',login);document.getElementById('apply')?.addEventListener('click',()=>{state.from=document.getElementById('from').value;state.to=document.getElementById('to').value;state.type=document.getElementById('type').value;state.point=document.getElementById('point').value;load()});document.getElementById('reset')?.addEventListener('click',()=>{state.from=monthStart();state.to=shift(0);state.type='';state.point='';load()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.open.has(b.dataset.open)?state.open.delete(b.dataset.open):state.open.add(b.dataset.open);render()});document.querySelectorAll('[data-history-type]').forEach(b=>b.onclick=()=>toggleHistory(b.dataset.historyType,b.dataset.historyId));document.querySelectorAll('[data-edit-type]').forEach(b=>b.onclick=()=>{const d=findDoc(b.dataset.editType,b.dataset.editId);if(!d)return;state.editing.has(historyKey(d))?saveEdit(d):startEdit(d)});document.querySelectorAll('[data-cancel-type]').forEach(b=>b.onclick=()=>{const d=findDoc(b.dataset.cancelType,b.dataset.cancelId);if(d)cancelEdit(d)});document.querySelectorAll('[data-draft-key]').forEach(inp=>inp.oninput=()=>{state.drafts[inp.dataset.draftKey]=inp.value});document.querySelectorAll('[data-actor-select]').forEach(sel=>sel.onchange=()=>{state.actor=sel.value;if(state.actor)localStorage.setItem('stolovaya:journal-actor',state.actor);else localStorage.removeItem('stolovaya:journal-actor')})}
function render(){root.innerHTML=state.data?app():loginScreen();bind()}
(async()=>{if(state.token)await load();else if(!(await bootstrapFromStolovaya()))render()})();
