const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('journal-app');
function shift(days){const d=new Date();d.setDate(d.getDate()+days);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow'}).format(d)}
function monthStart(){const today=shift(0);return today.slice(0,8)+'01'}
const state={token:localStorage.getItem('stolovaya:admin')||sessionStorage.getItem('stolovaya:admin')||'',pin:'',from:monthStart(),to:shift(0),type:'closing',point:'',data:null,busy:false,message:'',open:new Set(),historyOpen:new Set(),histories:{},historyBusy:new Set(),employees:[],actor:localStorage.getItem('stolovaya:journal-actor')||'',editing:new Set(),saving:new Set(),drafts:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Не удалось выполнить запрос');return d}
function saveAdminToken(t){state.token=t;localStorage.setItem('stolovaya:admin',t);sessionStorage.setItem('stolovaya:admin',t)} function clearAdminToken(){state.token='';localStorage.removeItem('stolovaya:admin');sessionStorage.removeItem('stolovaya:admin')}
async function bootstrapFromStolovaya(){const buffetToken=localStorage.getItem('stolovaya:web-token');if(!buffetToken)return false;try{const r=await rpc('public_admin_session_from_buffet_token',{p_token:buffetToken});saveAdminToken(r.token);await load();return true}catch(e){return false}}
async function login(){if(state.pin.length<4)return;state.busy=true;state.message='';render();try{const r=await rpc('public_admin_web_login',{p_pin:state.pin});saveAdminToken(r.token);state.pin='';await load()}catch(e){state.message=e.message;clearAdminToken()}finally{state.busy=false;render()}}
async function loadEmployees(){try{const d=await rpc('admin_employee_directory',{p_token:state.token});state.employees=(d.employees||[]).filter(e=>e.isActive)}catch(e){state.employees=[]}}
async function load(){if(!state.token)return;state.busy=true;state.message='';render();try{const [journal]=await Promise.all([rpc('admin_document_journal',{p_token:state.token,p_from:state.from,p_to:state.to,p_type:state.type||null,p_point_code:state.point||null}),state.employees.length?Promise.resolve():loadEmployees()]);state.data=journal}catch(e){state.data=null;state.message=e.message;if(/недействительн/i.test(state.message)){clearAdminToken();if(await bootstrapFromStolovaya())return}}finally{state.busy=false;render()}}
function loginScreen(){return `<main class="journal"><section class="card login"><h1>Журнал документов</h1><p>Если вы уже входили в «Столовую» на этом устройстве, журнал откроется автоматически. Иначе введите код доступа.</p><input id="pin" type="password" inputmode="numeric" value="${esc(state.pin)}" placeholder="Код доступа"><button id="login" ${state.busy||state.pin.length<4?'disabled':''}>${state.busy?'Входим…':'Войти'}</button>${state.message?`<p class="message">${esc(state.message)}</p>`:''}</section></main>`}
function typeName(t){return ({movement:'Перемещение',closing:'Закрытие дня',realization:'Акт реализации',utilization:'Акт утилизации',internal_transfer:'Внутреннее перемещение',freeze_in:'Заморозка',freeze_out:'Разморозка',freeze_adjustment:'Корректировка морозилки',correction:'Корректировка'})[t]||t}
function historyKey(d){return d.doc_type+'|'+d.doc_id} function itemQty(i){return i.qty??i.sent??i.leftover??i.received??''} function draftKey(d,i){return historyKey(d)+'|'+String(i.itemId)} function findDoc(type,id){return (state.data?.documents||[]).find(d=>d.doc_type===type&&String(d.doc_id)===String(id))}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function fmtQty(v){return num(v).toLocaleString('ru-RU',{maximumFractionDigits:3})}
function fmtMoney(v){return num(v).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₽'}
function groupedItemsHtml(items,docType){const groups=new Map();for(const i of items){const g=String(i.group||'Прочее').trim()||'Прочее';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(i)}const sorted=[...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ru'));let totalQty=0,totalSale=0,totalCost=0;const body=sorted.map(([group,rows])=>{const qty=rows.reduce((s,i)=>s+num(itemQty(i)),0);const sale=rows.reduce((s,i)=>s+num(i.saleValue),0);const cost=rows.reduce((s,i)=>s+num(i.costAmount),0);totalQty+=qty;totalSale+=sale;totalCost+=cost;return `<section class="doc-group"><div class="doc-group-head"><b>${esc(group)}</b><span>Итого: ${esc(fmtQty(qty))}${docType==='realization'&&sale?` · ${esc(fmtMoney(sale))}`:''}${docType==='utilization'&&cost?` · себест. ${esc(fmtMoney(cost))}`:''}</span></div><div class="items">${rows.slice().sort((a,b)=>String(a.dish||'').localeCompare(String(b.dish||''),'ru')).map(i=>`<div class="item-row"><span>${esc(i.dish||'')}</span><b>${esc(fmtQty(itemQty(i)))}</b></div>`).join('')}</div></section>`}).join('');const totalMoney=docType==='realization'&&totalSale?` · ${esc(fmtMoney(totalSale))}`:docType==='utilization'&&totalCost?` · себест. ${esc(fmtMoney(totalCost))}`:'';return `${body}<div class="doc-total"><b>ИТОГО ПО ДОКУМЕНТУ</b><span>${esc(fmtQty(totalQty))}${totalMoney}</span></div>`}
function details(d){const x=d.details||{},items=x.items||[];const grouped=(d.doc_type==='realization'||d.doc_type==='utilization');return `<div class="details"><div class="details-grid"><div><b>Тип</b><br>${esc(typeName(d.doc_type))}</div><div><b>Кто создал</b><br>${esc(d.actor||'—')}</div>${x.documentNumber?`<div><b>Номер документа</b><br>${esc(x.documentNumber)}</div>`:''}${x.iikoDocumentNumber?`<div><b>Номер в iiko</b><br>${esc(x.iikoDocumentNumber)}</div>`:''}${x.exportedAt?`<div><b>Отправлен в iiko</b><br>${esc(fmtAt(x.exportedAt))}</div>`:''}</div>${items.length?(grouped?groupedItemsHtml(items,d.doc_type):`<div class="items">${items.map(i=>`<div><span>${esc(i.dish||'')}</span><b>${esc(itemQty(i))}</b></div>`).join('')}</div>`):`<pre>${esc(JSON.stringify(x,null,2))}</pre>`}</div>`}
function fmtAt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
function sourceName(s){return ({mobile:'Приложение',database:'Система',iiko_xls:'iiko',iiko:'iiko',excel:'База',admin:'Администратор'})[s]||s||'—'}
function historyHtml(d){const key=historyKey(d);if(state.historyBusy.has(key))return `<div class="details"><p>Загружаем историю…</p></div>`;const info=state.histories[key];if(info?.error)return `<div class="details"><p class="message">${esc(info.error)}</p></div>`;const events=info?.events||[];if(!events.length)return `<div class="details"><p>История документа пока не зафиксирована.</p></div>`;return `<div class="details"><h3>История документа</h3><div class="items history-list">${events.map(e=>`<div><span><b>${esc(e.action||'Изменение')}</b><small>${esc(fmtAt(e.at))} · ${esc(e.actor||'Система')} · ${esc(sourceName(e.source))}${e.note?`<br>${esc(e.note)}`:''}</small></span></div>`).join('')}</div></div>`}
async function refreshHistory(d){const key=historyKey(d);state.historyBusy.add(key);render();try{state.histories[key]=await rpc('admin_document_history',{p_token:state.token,p_doc_type:d.doc_type,p_doc_id:String(d.doc_id)})}catch(e){state.histories[key]={events:[],error:e.message}}finally{state.historyBusy.delete(key);render()}}
async function toggleHistory(type,id){const d=findDoc(type,id);if(!d)return;const key=historyKey(d);if(state.historyOpen.has(key)){state.historyOpen.delete(key);render();return}state.historyOpen.add(key);if(!state.histories[key])await refreshHistory(d);else render()}
function app(){const docs=state.data?.documents||[];return `<main class="journal"><header class="top"><div><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Журнал документов</h1></div><a class="back secondary" href="../">Назад</a></header><section class="card"><div class="filters"><label>С<input id="from" type="date" value="${state.from}"></label><label>По<input id="to" type="date" value="${state.to}"></label><label>Тип<select id="type"><option value="">Все документы</option>${(state.data?.types||[]).map(t=>`<option value="${esc(t.code)}" ${state.type===t.code?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Точка<select id="point"><option value="">Все точки</option>${(state.data?.points||[]).map(p=>`<option value="${esc(p.code)}" ${state.point===p.code?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label></div><div class="actions"><button id="apply">Применить</button><button id="reset" class="secondary">Сбросить</button></div></section><section class="card summary"><span>Документов: <b>${docs.length}</b></span><span>${esc(state.from)} — ${esc(state.to)}</span></section>${state.message?`<p class="message">${esc(state.message)}</p>`:''}<section class="docs">${docs.length?docs.map(d=>{const k=historyKey(d);return `<article class="doc"><div class="doc-head"><div class="doc-date">${esc(d.business_date)}</div><div class="doc-title"><b>${esc(d.title)}</b><small>${esc(typeName(d.doc_type))}</small></div><div>${esc(d.from_point||'')} ${d.from_point&&d.to_point?'→ ':''}${esc(d.to_point||'')}</div><button data-open="${esc(k)}">${state.open.has(k)?'Скрыть документ':'Открыть'}</button><button class="secondary" data-history-type="${esc(d.doc_type)}" data-history-id="${esc(d.doc_id)}">${state.historyOpen.has(k)?'Скрыть историю':'История документа'}</button></div>${state.open.has(k)?details(d):''}${state.historyOpen.has(k)?historyHtml(d):''}</article>`}).join(''):'<div class="card empty">За выбранный период документов нет.</div>'}</section></main>`}
function bind(){const p=document.getElementById('pin');if(p){p.oninput=e=>{state.pin=e.target.value.replace(/\D/g,'').slice(0,8);document.getElementById('login').disabled=state.pin.length<4};p.onkeydown=e=>{if(e.key==='Enter')login()}}document.getElementById('login')?.addEventListener('click',login);document.getElementById('apply')?.addEventListener('click',()=>{state.from=document.getElementById('from').value;state.to=document.getElementById('to').value;state.type=document.getElementById('type').value;state.point=document.getElementById('point').value;load()});document.getElementById('reset')?.addEventListener('click',()=>{state.from=monthStart();state.to=shift(0);state.type='closing';state.point='';load()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.open.has(b.dataset.open)?state.open.delete(b.dataset.open):state.open.add(b.dataset.open);render()});document.querySelectorAll('[data-history-type]').forEach(b=>b.onclick=()=>toggleHistory(b.dataset.historyType,b.dataset.historyId))}
function render(){root.innerHTML=state.data?app():loginScreen();bind()} (async()=>{if(state.token)await load();else if(!(await bootstrapFromStolovaya()))render()})();
