(()=>{
  const STYLE=`<style id="buffet-help-style">
  .buffet-help-btn{width:100%;margin-top:12px;border:1px solid #ded9cc;border-radius:16px;padding:14px 16px;background:#fff;color:#315f49;font-weight:700;display:flex;align-items:center;justify-content:center;gap:8px}
  .buffet-help-overlay{position:fixed;inset:0;z-index:9999;background:rgba(24,32,27,.42);display:flex;align-items:flex-end;justify-content:center;padding:12px}
  .buffet-help-modal{width:min(100%,720px);max-height:92vh;overflow:auto;background:#f6f3ea;border-radius:22px 22px 16px 16px;padding:16px;box-shadow:0 18px 60px rgba(0,0,0,.22)}
  .buffet-help-head{position:sticky;top:-16px;z-index:2;background:#f6f3ea;padding:14px 0 10px;display:flex;justify-content:space-between;align-items:center;gap:12px}
  .buffet-help-head h2{margin:0;color:#315f49;font:700 26px Georgia,serif}.buffet-help-close{border:0;border-radius:12px;background:#fff;color:#315f49;padding:10px 14px;font-weight:700}
  .buffet-help-intro{background:#edf5ec;border:1px solid #cbdcc9;border-radius:14px;padding:13px;line-height:1.45;margin-bottom:12px}
  .buffet-help-item{background:#fff;border:1px solid #ded9cc;border-radius:14px;margin-bottom:9px;overflow:hidden}
  .buffet-help-item summary{cursor:pointer;padding:14px 15px;font-weight:700;color:#315f49;list-style:none}.buffet-help-item summary::-webkit-details-marker{display:none}.buffet-help-item summary:after{content:'+';float:right;font-size:22px;line-height:16px}.buffet-help-item[open] summary:after{content:'−'}
  .buffet-help-body{padding:0 15px 15px;color:#445048;line-height:1.5}.buffet-help-body p{margin:8px 0}.buffet-help-body strong{color:#24322a}.buffet-help-note{background:#fff7df;border:1px solid #ead79a;border-radius:12px;padding:10px 12px;margin-top:10px}
  @media(min-width:700px){.buffet-help-overlay{align-items:center}.buffet-help-modal{border-radius:22px}}
  </style>`;
  const HELP=`<div class="buffet-help-overlay" id="buffet-help-overlay" role="dialog" aria-modal="true" aria-label="Инструкция по работе">
    <div class="buffet-help-modal">
      <div class="buffet-help-head"><h2>Как работать в приложении</h2><button class="buffet-help-close" id="buffet-help-close">Закрыть</button></div>
      <div class="buffet-help-intro"><strong>Главное:</strong> указывайте только фактические данные. Продажи считать вручную не нужно — приложение посчитает их само.</div>
      <details class="buffet-help-item" open><summary>1. Начало работы</summary><div class="buffet-help-body"><p>Выберите свою точку и проверьте дату. Обычно открывается сегодняшний день. Если нужно внести данные за вчера, сначала выберите вчерашнюю дату.</p><p><strong>Перед любой операцией проверьте точку и дату.</strong></p></div></details>
      <details class="buffet-help-item"><summary>2. Получили блюда с кухни</summary><div class="buffet-help-body"><p>Перемещения из iiko загружаются автоматически. В разделе <strong>«Посмотреть остатки»</strong> видно, сколько блюд доступно сегодня.</p><p>Если фактически приехало другое количество, не исправляйте документ самостоятельно — сообщите администратору.</p></div></details>
      <details class="buffet-help-item"><summary>3. Передаёте блюда на другую точку</summary><div class="buffet-help-body"><p>Нажмите <strong>«Создать перемещение»</strong>, выберите точку, блюдо и фактическое количество.</p><p>После отправки это количество сразу уменьшится на вашей точке.</p><p>Получающая точка должна принять перемещение <strong>по факту</strong>. Если отправили 10, а приехало 9 — принимаем 9.</p></div></details>
      <details class="buffet-help-item"><summary>4. Достали блюда из заморозки</summary><div class="buffet-help-body"><p>При сдаче остатков на вопрос <strong>«Доставали блюда из заморозки?»</strong> выберите «Да», укажите блюдо и количество.</p><p>Это количество спишется из заморозки и добавится к доступным сегодня блюдам.</p><div class="buffet-help-note"><strong>Важно:</strong> повторно замораживать уже размороженное блюдо нельзя.</div></div></details>
      <details class="buffet-help-item"><summary>5. Закрытие смены</summary><div class="buffet-help-body"><p>В конце дня нажмите <strong>«Сдать остатки»</strong>. Для каждого блюда укажите:</p><p><strong>Осталось</strong> — пойдёт на продажу завтра.<br><strong>Утиль</strong> — списываем.<br><strong>Заморозка</strong> — отправляем в морозилку.</p><p>Продажи вводить не нужно. Приложение рассчитает их автоматически.</p></div></details>
      <details class="buffet-help-item"><summary>6. Если блюда не осталось</summary><div class="buffet-help-body"><div class="buffet-help-note"><strong>Обязательно поставьте 0 в поле «Осталось».</strong><br>Пустое поле означает, что позиция ещё не посчитана. Ноль означает, что вы посчитали и блюда действительно нет.</div></div></details>
      <details class="buffet-help-item"><summary>7. Если утиля или заморозки не было</summary><div class="buffet-help-body"><p>Поля «Утиль» и «Заморозка» можно оставить пустыми. Но <strong>«Осталось» должно быть заполнено всегда</strong>, даже если там 0.</p></div></details>
      <details class="buffet-help-item"><summary>8. Проверка перед сдачей</summary><div class="buffet-help-body"><p>Проверьте дату, точку, все остатки, утиль и заморозку. После этого нажмите <strong>«Сдать всё»</strong>.</p><p>Если заполнена только часть позиций, можно использовать <strong>«Сохранить посчитанное»</strong> и закончить позже.</p></div></details>
      <details class="buffet-help-item"><summary>9. Если нашли ошибку после сдачи</summary><div class="buffet-help-body"><p>Не исправляйте ошибку следующим днём. Нужно корректировать именно тот день, где она произошла.</p><p>Если дата доступна — внесите корректировку. Если период уже закрыт — обратитесь к администратору.</p></div></details>
      <details class="buffet-help-item"><summary>10. Если забыли закрыть вчера</summary><div class="buffet-help-body"><p>Выберите вчерашнюю дату и внесите фактические остатки на конец вчерашней смены. Если период уже закрыт, потребуется помощь администратора.</p></div></details>
    </div></div>`;
  function openHelp(){if(document.getElementById('buffet-help-overlay'))return;document.body.insertAdjacentHTML('beforeend',HELP);document.getElementById('buffet-help-close')?.addEventListener('click',closeHelp);document.getElementById('buffet-help-overlay')?.addEventListener('click',e=>{if(e.target.id==='buffet-help-overlay')closeHelp()});document.body.style.overflow='hidden'}
  function closeHelp(){document.getElementById('buffet-help-overlay')?.remove();document.body.style.overflow=''}
  function mount(){if(!document.getElementById('buffet-help-style'))document.head.insertAdjacentHTML('beforeend',STYLE);const actions=document.querySelector('.home-actions');if(!actions||document.getElementById('buffet-help-btn'))return;const btn=document.createElement('button');btn.id='buffet-help-btn';btn.className='buffet-help-btn';btn.type='button';btn.innerHTML='<span>?</span> Как работать';btn.addEventListener('click',openHelp);actions.insertAdjacentElement('afterend',btn)}
  new MutationObserver(mount).observe(document.getElementById('app'),{childList:true,subtree:true});mount();
})();