const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('admin-app');
const employeeMode=/\/admin\/employees\/?$/i.test(location.pathname);
const state={token:sessionStorage.getItem('stolovaya:admin')||'',pin:'',directory:null,busy:false,message:'',edit:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Операция не выполнена');return d}
async function adminLogin(){if(state.pin.length<4)return;state.busy=true;state.message='';render();try{const r=await rpc('public_admin_web_login',{p_pin:state.pin});state.token=r.token;sessionStorage.setItem('stolovaya:admin',state.token);state.pin='';await load()}catch(e){state.token='';sessionStorage.removeItem('stolovaya:admin');state.message=e.message||'Не удалось войти'}finally{state.busy=false;render()}}
async function load(){if(!state.token)return;state.busy=true;state.message='';render();try{state.directory=await rpc('admin_employee_directory',{p_token:state.token});sessionStorage.setItem('stolovaya:admin',state.token)}catch(e){state.directory=null;state.token='';sessionStorage.removeItem('stolovaya:admin');state.message='Сессия администратора недействительна. Введите код доступа.'}finally{state.busy=false;render()}}
async function sessionFromBuffet(){const buffetToken=localStorage.getItem('stolovaya:web-token')||'';if(!buffetToken)return false;try{const r=await rpc('public_admin_session_from_buffet_token',{p_token:buffetToken});if(!r?.token)return false;state.token=r.token;sessionStorage.setItem('stolovaya:admin',state.token);await load();return !!state.directory}catch(e){console.error('Admin session exchange failed',e);return false}}
function emptyDraft(){return{id:null,fullName:'',login:'',isActive:true,roles:new Set(['buffet']),points:new Set()}}
function editEmployee(x){state.edit={id:x.id,fullName:x.fullName,login:x.login||'',isActive:x.isActive,roles:new Set(x.roles),points:new Set(x.points.map(p=>p.pointCode))};render()}
async function save(){const d=state.edit;if(!d||!d.fullName.trim()||!d.roles.size)return;state.busy=true;state.message='';render();try{await rpc('admin_save_employee',{p_token:state.token,p_employee_id:d.id,p_full_name:d.fullName,p_login:d.login||null,p_is_active:d.isActive,p_roles:[...d.roles],p_point_codes:[...d.points],p_actor:'Администратор'});state.edit=null;await load();state.message='Сотрудник сохранён'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function setActive(x,value){state.busy=true;render();try{await rpc('admin_set_employee_active',{p_token:state.token,p_employee_id:x.id,p_is_active:value,p_actor:'Администратор'});await load()}catch(e){state.message=e.message}finally{state.busy=false;render()}}
function login(){return `<main class="admin"><section class="card login"><h1>Администратор</h1><p>Если вы уже вошли в «Столовую» на этом устройстве, админка откроется автоматически. Иначе введите тот же код доступа.</p><input id="pin" type="password" inputmode="numeric" autocomplete="one-time-code" value="${esc(state.pin)}" placeholder="Код доступа"><button id="open" ${state.busy||state.pin.length<4?'disabled':''}>${state.busy?'Проверяем…':'Войти'}</button>${state.message?`<p class="message">${esc(state.message)}</p>`:''}</section></main>`}
function form(){const d=state.edit||emptyDraft();const points=state.directory?.points||[];return `<section class="card"><h2>${d.id?'Редактирование':'Новый сотрудник'}</h2><div class="employee-form"><input id="full-name" value="${esc(d.fullName)}" placeholder="ФИО"><input id="login-name" value="${esc(d.login)}" placeholder="Логин (необязательно)"><div class="roles"><label><input type="checkbox" data-role="buffet" ${d.roles.has('buffet')?'checked':''}>Буфетчик</label><label><input type="checkbox" data-role="admin" ${d.roles.has('admin')?'checked':''}>Администратор</label><label><input id="active" type="checkbox" ${d.isActive?'checked':''}>Активен</label></div><b>Доступные точки для буфетчика</b><div class="points">${points.map(p=>`<label><input type="checkbox" data-access="${p.pointCode}" ${d.points.has(p.pointCode)?'checked':''}>${esc(p.pointName)}</label>`).join('')}</div><div class="form-actions"><button id="save" ${state.busy?'disabled':''}>Сохранить</button><button id="cancel" class="secondary">Отмена</button></div></div></section>`}
function home(){return `<main class="admin"><header class="top"><div><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Управление</h1><p class="subtitle">Выберите раздел</p></div><button id="logout" class="secondary">Выйти</button></header>${state.message?`<p class="message">${esc(state.message)}</p>`:''}<section class="admin-menu"><a class="menu-card" href="report/"><span class="menu-icon">▦</span><div><b>Главный отчёт</b><small>Остатки, движение, продажи и заморозка</small></div><span class="menu-arrow">›</span></a><a class="menu-card" href="journal/"><span class="menu-icon">≡</span><div><b>Журнал документов</b><small>Закрытия, перемещения, заморозка и история</small></div><span class="menu-arrow">›</span></a><a class="menu-card" href="employees/"><span class="menu-icon">👥</span><div><b>Сотрудники</b><small>Роли, доступы к точкам и активность</small></div><span class="menu-arrow">›</span></a></section></main>`}
function employees(){return `<main class="admin"><header class="top"><div><a class="section-back" href="../">← Назад в админку</a><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Сотрудники</h1><p class="subtitle">Управление сотрудниками и доступами</p></div><button id="logout" class="secondary">Выйти</button></header><section class="card section-actions"><div><b>Всего сотрудников: ${state.directory.employees.length}</b><small>Активных: ${state.directory.employees.filter(x=>x.isActive).length}</small></div><button id="new">＋ Добавить сотрудника</button></section>${state.message?`<p class="message">${esc(state.message)}</p>`:''}${state.edit?form():''}<section class="card"><div class="employee-grid">${state.directory.employees.map(x=>`<article class="employee"><div class="employee-head"><div><b>${esc(x.fullName)}</b><div class="badges">${x.roles.includes('buffet')?'<span class="badge">Буфетчик</span>':''}${x.roles.includes('admin')?'<span class="badge">Администратор</span>':''}${!x.isActive?'<span class="badge muted">Отключён</span>':''}</div></div><div class="employee-actions"><button class="secondary edit" data-id="${x.id}">Изменить</button><button class="secondary active-toggle" data-id="${x.id}">${x.isActive?'Отключить':'Включить'}</button></div></div><small>Точки: ${x.points.length?x.points.map(p=>p.pointName).join(', '):'не назначены'}</small></article>`).join('')}</div></section></main>`}
function app(){return employeeMode?employees():home()}
function bind(){const p=document.getElementById('pin');if(p){p.oninput=e=>{state.pin=e.target.value.replace(/\D/g,'').slice(0,8);document.getElementById('open').disabled=state.pin.length<4};p.onkeydown=e=>{if(e.key==='Enter')adminLogin()}}document.getElementById('open')?.addEventListener('click',adminLogin);document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem('stolovaya:admin');state.token='';state.directory=null;state.edit=null;render()});document.getElementById('new')?.addEventListener('click',()=>{state.edit=emptyDraft();render()});document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editEmployee(state.directory.employees.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.active-toggle').forEach(b=>{const x=state.directory.employees.find(v=>v.id===b.dataset.id);b.onclick=()=>setActive(x,!x.isActive)});if(state.directory&&state.edit){const d=state.edit;document.getElementById('full-name')?.addEventListener('input',e=>d.fullName=e.target.value);document.getElementById('login-name')?.addEventListener('input',e=>d.login=e.target.value);document.getElementById('active')?.addEventListener('change',e=>d.isActive=e.target.checked);document.querySelectorAll('[data-role]').forEach(i=>i.onchange=()=>i.checked?d.roles.add(i.dataset.role):d.roles.delete(i.dataset.role));document.querySelectorAll('[data-access]').forEach(i=>i.onchange=()=>i.checked?d.points.add(i.dataset.access):d.points.delete(i.dataset.access));document.getElementById('save')?.addEventListener('click',save);document.getElementById('cancel')?.addEventListener('click',()=>{state.edit=null;render()})}}
function render(){root.innerHTML=state.directory?app():login();bind()}
(async()=>{if(state.token){await load();if(state.directory)return}state.message='';const ok=await sessionFromBuffet();if(!ok)render()})();
