const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('admin-app');
const state={token:sessionStorage.getItem('stolovaya:admin')||'',directory:null,busy:false,message:'',edit:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Операция не выполнена');return d}
async function load(){if(!state.token)return;state.busy=true;state.message='';render();try{state.directory=await rpc('admin_employee_directory',{p_token:state.token});sessionStorage.setItem('stolovaya:admin',state.token)}catch(e){state.directory=null;state.message=e.message}finally{state.busy=false;render()}}
function emptyDraft(){return{id:null,fullName:'',login:'',isActive:true,roles:new Set(['buffet']),points:new Set()}}
function editEmployee(x){state.edit={id:x.id,fullName:x.fullName,login:x.login||'',isActive:x.isActive,roles:new Set(x.roles),points:new Set(x.points.map(p=>p.pointCode))};render()}
async function save(){const d=state.edit;if(!d||!d.fullName.trim()||!d.roles.size)return;state.busy=true;state.message='';render();try{await rpc('admin_save_employee',{p_token:state.token,p_employee_id:d.id,p_full_name:d.fullName,p_login:d.login||null,p_is_active:d.isActive,p_roles:[...d.roles],p_point_codes:[...d.points],p_actor:'Администратор'});state.edit=null;await load();state.message='Сотрудник сохранён'}catch(e){state.message=e.message}finally{state.busy=false;render()}}
async function setActive(x,value){state.busy=true;render();try{await rpc('admin_set_employee_active',{p_token:state.token,p_employee_id:x.id,p_is_active:value,p_actor:'Администратор'});await load()}catch(e){state.message=e.message}finally{state.busy=false;render()}}
function login(){return `<main class="admin"><section class="card login"><h1>Администратор</h1><p>Введите ключ администратора.</p><input id="token" type="password" value="${esc(state.token)}" placeholder="Ключ администратора"><button id="open" ${state.busy||!state.token?'disabled':''}>${state.busy?'Проверяем…':'Войти'}</button>${state.message?`<p class="message">${esc(state.message)}</p>`:''}</section></main>`}
function form(){const d=state.edit||emptyDraft();const points=state.directory?.points||[];return `<section class="card"><h2>${d.id?'Редактирование':'Новый сотрудник'}</h2><div class="employee-form"><input id="full-name" value="${esc(d.fullName)}" placeholder="ФИО"><input id="login-name" value="${esc(d.login)}" placeholder="Логин (необязательно)"><div class="roles"><label><input type="checkbox" data-role="buffet" ${d.roles.has('buffet')?'checked':''}>Буфетчик</label><label><input type="checkbox" data-role="admin" ${d.roles.has('admin')?'checked':''}>Администратор</label><label><input id="active" type="checkbox" ${d.isActive?'checked':''}>Активен</label></div><b>Доступные точки для буфетчика</b><div class="points">${points.map(p=>`<label><input type="checkbox" data-access="${p.pointCode}" ${d.points.has(p.pointCode)?'checked':''}>${esc(p.pointName)}</label>`).join('')}</div><div class="form-actions"><button id="save" ${state.busy?'disabled':''}>Сохранить</button>${d.id?'<button id="cancel" class="secondary">Отмена</button>':''}</div></div></section>`}
function app(){return `<main class="admin"><header class="top"><div><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Управление</h1></div><button id="logout" class="secondary">Выйти</button></header><section class="card nav"><a class="admin-link" href="report/">Главный отчёт</a><button id="new" class="secondary">Добавить сотрудника</button></section>${state.message?`<p class="message">${esc(state.message)}</p>`:''}<section class="card"><h2>Сотрудники</h2><div class="employee-grid">${state.directory.employees.map(x=>`<article class="employee"><div class="employee-head"><div><b>${esc(x.fullName)}</b><div class="badges">${x.roles.includes('buffet')?'<span class="badge">Буфетчик</span>':''}${x.roles.includes('admin')?'<span class="badge">Администратор</span>':''}${!x.isActive?'<span class="badge">Отключён</span>':''}</div></div><div><button class="secondary edit" data-id="${x.id}">Изменить</button> <button class="secondary active-toggle" data-id="${x.id}">${x.isActive?'Отключить':'Включить'}</button></div></div><small>Точки: ${x.points.length?x.points.map(p=>p.pointName).join(', '):'не назначены'}</small></article>`).join('')}</div></section>${form()}</main>`}
function bind(){const t=document.getElementById('token');if(t)t.oninput=e=>{state.token=e.target.value;document.getElementById('open').disabled=!state.token};document.getElementById('open')?.addEventListener('click',load);document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem('stolovaya:admin');state.token='';state.directory=null;state.edit=null;render()});document.getElementById('new')?.addEventListener('click',()=>{state.edit=emptyDraft();render()});document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editEmployee(state.directory.employees.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.active-toggle').forEach(b=>{const x=state.directory.employees.find(v=>v.id===b.dataset.id);b.onclick=()=>setActive(x,!x.isActive)});if(state.directory){const d=state.edit||emptyDraft();document.getElementById('full-name')?.addEventListener('input',e=>{if(!state.edit)state.edit=d;state.edit.fullName=e.target.value});document.getElementById('login-name')?.addEventListener('input',e=>{if(!state.edit)state.edit=d;state.edit.login=e.target.value});document.getElementById('active')?.addEventListener('change',e=>{if(!state.edit)state.edit=d;state.edit.isActive=e.target.checked});document.querySelectorAll('[data-role]').forEach(i=>i.onchange=()=>{if(!state.edit)state.edit=d;i.checked?state.edit.roles.add(i.dataset.role):state.edit.roles.delete(i.dataset.role)});document.querySelectorAll('[data-access]').forEach(i=>i.onchange=()=>{if(!state.edit)state.edit=d;i.checked?state.edit.points.add(i.dataset.access):state.edit.points.delete(i.dataset.access)});document.getElementById('save')?.addEventListener('click',()=>{if(!state.edit)state.edit=d;save()});document.getElementById('cancel')?.addEventListener('click',()=>{state.edit=null;render()})}}
function render(){root.innerHTML=state.directory?app():login();bind()}
if(state.token)load();else render();
