const API='https://rgluzdxikpagugpmusbp.supabase.co/rest/v1/rpc';
const KEY='sb_publishable_rcvNssgN4_dPnVUpjU0bjQ_1cEWsA52';
const root=document.getElementById('report-app');
const groupOrder=['Холодные закуски','Первые блюда','Блюда для завтраков','Вторые блюда','Гарниры','Напитки','Хлеб','Дополнительный ассортимент','Выпечка','Прочее'];
const state={token:sessionStorage.getItem('stolovaya:admin')||'',pin:'',mode:'day',date:today(),from:today(),to:today(),report:null,selected:new Set(),collapsed:new Set(),busy:false,message:''};
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow'}).format(new Date())}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v==null?'—':Number(v).toLocaleString('ru-RU',{maximumFractionDigits:3});
async function rpc(name,body){const r=await fetch(`${API}/${name}`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Не удалось сформировать отчёт');return d}
async function adminLogin(){if(state.pin.length<4)return;state.busy=true;state.message='';render();try{const r=await rpc('public_admin_web_login',{p_pin:state.pin});state.token=r.token;state.pin='';sessionStorage.setItem('stolovaya:admin',state.token);await load()}catch(e){state.token='';sessionStorage.removeItem('stolovaya:admin');state.message=e.message||'Не удалось войти'}finally{state.busy=false;render()}}
async function load(){if(!state.token)return;if(state.mode==='range'&&state.from>state.to){state.message='Дата «с» не может быть позже даты «по»';return render()}state.busy=true;state.message='';render();try{state.report=state.mode==='day'?await rpc('admin_main_operational_report',{p_token:state.token,p_business_date:state.date}):await rpc('admin_main_operational_report_range',{p_token:state.token,p_from:state.from,p_to:state.to});sessionStorage.setItem('stolovaya:admin',state.token);if(!state.selected.size)state.selected=new Set(state.report.points.map(p=>p.code));else state.selected=new Set([...state.selected].filter(x=>state.report.points.some(p=>p.code===x)))}catch(e){state.report=null;state.token='';sessionStorage.removeItem('stolovaya:admin');state.message='Сессия администратора недействительна. Введите код доступа.'}finally{state.busy=false;render()}}
function groups(rows){const m=new Map();for(const r of rows){const g=r.group_name||'Прочее';if(!m.has(g))m.set(g,new Map());m.get(g).set(r.dish_id,r.dish_name)}return [...m.entries()].sort(([a],[b])=>{const ai=groupOrder.indexOf(a),bi=groupOrder.indexOf(b);return (ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'ru')}).map(([name,d])=>({name,dishes:[...d.entries()].map(([id,name])=>({id,name})).sort((a,b)=>a.name.localeCompare(b.name,'ru'))}))}
function points(){return state.report?.points.filter(p=>state.selected.has(p.code))||[]}
function row(id,code){return state.report?.rows.find(r=>r.dish_id===id&&r.point_code===code)}
function frow(id,code){return state.report?.freezer.find(r=>r.dish_id===id&&r.point_code===code)}
function toggleAll(){if(!state.report)return;state.selected=state.selected.size===state.report.points.length?new Set():new Set(state.report.points.map(p=>p.code));render()}
function togglePoint(code){state.selected.has(code)?state.selected.delete(code):state.selected.add(code);render()}
function toggleGroup(g){state.collapsed.has(g)?state.collapsed.delete(g):state.collapsed.add(g);render()}
function exportCsv(){if(!state.report)return;const ps=points(),gs=groups(state.report.rows);const head=['Группа','Номенклатура',...ps.flatMap(p=>[`${p.name} — Остаток на начало`,`${p.name} — Пришло`,`${p.name} — Остаток`,`${p.name} — Утиль`,`${p.name} — Заморозка`,`${p.name} — Продано`])];const lines=[head,...gs.flatMap(g=>g.dishes.map(d=>[g.name,d.name,...ps.flatMap(p=>{const r=row(d.id,p.code);return [r?.opening_qty??0,r?.received_qty??0,r?.leftover_qty??'',r?.waste_qty??'',r?.frozen_qty??'',r?.sold_qty??'']})]))];const csv='\ufeff'+lines.map(x=>x.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`stolovaya-report-${state.mode==='day'?state.date:`${state.from}-${state.to}`}.csv`;a.click();URL.revokeObjectURL(a.href)}
function login(){return `<main class="report"><section class="card login"><h1>Главный отчёт администратора</h1><p>Введите тот же код доступа, который используете для входа в «Столовую».</p><input id="admin-pin" type="password" inputmode="numeric" autocomplete="one-time-code" value="${esc(state.pin)}" placeholder="Код доступа"><button id="open" ${state.busy||state.pin.length<4?'disabled':''}>${state.busy?'Проверяем…':'Открыть отчёт'}</button>${state.message?`<p class="message">${esc(state.message)}</p>`:''}</section></main>`}
function matrix(){const ps=points();if(!ps.length)return '<section class="card empty">Выберите хотя бы одну точку.</section>';const gs=groups(state.report.rows);return `<section class="card section"><h2>Основной отчёт</h2><div class="wrap"><table class="matrix"><thead><tr><th class="sticky" rowspan="2">Номенклатура</th>${ps.map(p=>`<th colspan="6">${esc(p.name)}</th>`).join('')}</tr><tr>${ps.map(()=>['Остаток на начало','Пришло','Остаток','Утиль','Заморозка','Итого продано'].map(h=>`<th>${h}</th>`).join('')).join('')}</tr></thead><tbody>${gs.map(g=>`<tr class="group-row" data-group="${encodeURIComponent(g.name)}"><td class="sticky">${state.collapsed.has(g.name)?'＋':'−'} ${esc(g.name)}</td><td colspan="${ps.length*6}"></td></tr>${state.collapsed.has(g.name)?'':g.dishes.map(d=>`<tr><td class="sticky dish">${esc(d.name)}</td>${ps.map(p=>{const r=row(d.id,p.code);return `<td>${fmt(r?.opening_qty)}</td><td title="Кухня: ${fmt(r?.kitchen_in_qty)}; принято: ${fmt(r?.internal_in_qty)}; отправлено: ${fmt(r?.internal_out_qty)}; разморожено: ${fmt(r?.thawed_qty)}">${fmt(r?.received_qty)}</td><td>${fmt(r?.leftover_qty)}</td><td>${fmt(r?.waste_qty)}</td><td>${fmt(r?.frozen_qty)}</td><td class="sold">${fmt(r?.sold_qty)}</td>`}).join('')}</tr>`).join('')}`).join('')}<tr class="total"><td class="sticky">ИТОГО</td>${ps.map(p=>{const rs=state.report.rows.filter(r=>r.point_code===p.code);const sum=k=>rs.reduce((s,r)=>s+Number(r[k]||0),0);return `<td>${fmt(sum('opening_qty'))}</td><td>${fmt(sum('received_qty'))}</td><td>${fmt(sum('leftover_qty'))}</td><td>${fmt(sum('waste_qty'))}</td><td>${fmt(sum('frozen_qty'))}</td><td>${fmt(sum('sold_qty'))}</td>`}).join('')}</tr></tbody></table></div></section>`}
function freezer(){const ps=points();if(!ps.length)return '';const gs=groups(state.report.freezer.filter(r=>state.selected.has(r.point_code)));return `<section class="card section"><h2>Заморозка</h2><div class="wrap"><table class="matrix"><thead><tr><th class="sticky" rowspan="2">Номенклатура</th>${ps.map(p=>`<th colspan="4">${esc(p.name)}</th>`).join('')}</tr><tr>${ps.map(()=>['Остаток на начало','Разморозили','Заморозили','Остаток на конец'].map(h=>`<th>${h}</th>`).join('')).join('')}</tr></thead><tbody>${gs.length?gs.map(g=>`<tr class="group-row"><td class="sticky">${esc(g.name)}</td><td colspan="${ps.length*4}"></td></tr>${g.dishes.map(d=>`<tr><td class="sticky dish">${esc(d.name)}</td>${ps.map(p=>{const r=frow(d.id,p.code);return `<td>${fmt(r?.opening_qty)}</td><td>${fmt(r?.thawed_qty)}</td><td>${fmt(r?.frozen_qty)}</td><td>${fmt(r?.closing_qty)}</td>`}).join('')}</tr>`).join('')}`).join(''):`<tr><td class="sticky">Нет движения по заморозке</td><td colspan="${ps.length*4}"></td></tr>`}</tbody></table></div></section>`}
function report(){const all=state.report.points.length===state.selected.size;return `<main class="report"><header class="top"><div><small>СТОЛОВАЯ • АДМИНИСТРАТОР</small><h1>Главный операционный отчёт</h1></div><a href="../">Сотрудники</a></header><section class="card period"><div class="period-mode"><button data-mode="day" class="${state.mode==='day'?'active':''}">День</button><button data-mode="range" class="${state.mode==='range'?'active':''}">Интервал</button></div>${state.mode==='day'?`<label><span>Дата</span><input id="day" type="date" value="${state.date}"></label>`:`<label><span>С</span><input id="from" type="date" value="${state.from}" max="${state.to}"></label><label><span>По</span><input id="to" type="date" value="${state.to}" min="${state.from}"></label>`}</section><section class="card points"><div class="point-title"><b>Точки</b><button id="all">${all?'Снять все':'Выбрать все'}</button></div><div class="checks">${state.report.points.map(p=>`<label><input type="checkbox" data-point="${p.code}" ${state.selected.has(p.code)?'checked':''}><span>${esc(p.name)}</span></label>`).join('')}</div></section><div class="actions"><button id="excel">Excel</button><button id="print">Печать / PDF</button><button id="logout">Выйти</button></div>${matrix()}${freezer()}${state.message?`<p class="message">${esc(state.message)}</p>`:''}</main>`}
function bind(){const p=document.getElementById('admin-pin');if(p){p.oninput=e=>{state.pin=e.target.value.replace(/\D/g,'').slice(0,8);document.getElementById('open').disabled=state.pin.length<4};p.onkeydown=e=>{if(e.key==='Enter')adminLogin()}}document.getElementById('open')?.addEventListener('click',adminLogin);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;load()});const day=document.getElementById('day');if(day)day.onchange=e=>{state.date=e.target.value;load()};const from=document.getElementById('from');if(from)from.onchange=e=>{state.from=e.target.value;if(state.from<=state.to)load();else render()};const to=document.getElementById('to');if(to)to.onchange=e=>{state.to=e.target.value;if(state.from<=state.to)load();else render()};document.getElementById('all')?.addEventListener('click',toggleAll);document.querySelectorAll('[data-point]').forEach(x=>x.onchange=()=>togglePoint(x.dataset.point));document.querySelectorAll('.group-row[data-group]').forEach(x=>x.onclick=()=>toggleGroup(decodeURIComponent(x.dataset.group)));document.getElementById('excel')?.addEventListener('click',exportCsv);document.getElementById('print')?.addEventListener('click',()=>window.print());document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem('stolovaya:admin');state.token='';state.report=null;render()})}
function render(){root.innerHTML=state.report?report():login();bind()}
if(state.token)load();else render();
